// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/drivers/proto/pointcloud.proto
// Protobuf Java Version: 4.26.1

package apollo.drivers;

public final class Pointcloud {
  private Pointcloud() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      Pointcloud.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PointXYZITOrBuilder extends
      // @@protoc_insertion_point(interface_extends:apollo.drivers.PointXYZIT)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional float x = 1 [default = nan];</code>
     * @return Whether the x field is set.
     */
    boolean hasX();
    /**
     * <code>optional float x = 1 [default = nan];</code>
     * @return The x.
     */
    float getX();

    /**
     * <code>optional float y = 2 [default = nan];</code>
     * @return Whether the y field is set.
     */
    boolean hasY();
    /**
     * <code>optional float y = 2 [default = nan];</code>
     * @return The y.
     */
    float getY();

    /**
     * <code>optional float z = 3 [default = nan];</code>
     * @return Whether the z field is set.
     */
    boolean hasZ();
    /**
     * <code>optional float z = 3 [default = nan];</code>
     * @return The z.
     */
    float getZ();

    /**
     * <code>optional uint32 intensity = 4 [default = 0];</code>
     * @return Whether the intensity field is set.
     */
    boolean hasIntensity();
    /**
     * <code>optional uint32 intensity = 4 [default = 0];</code>
     * @return The intensity.
     */
    int getIntensity();

    /**
     * <code>optional uint64 timestamp = 5 [default = 0];</code>
     * @return Whether the timestamp field is set.
     */
    boolean hasTimestamp();
    /**
     * <code>optional uint64 timestamp = 5 [default = 0];</code>
     * @return The timestamp.
     */
    long getTimestamp();
  }
  /**
   * Protobuf type {@code apollo.drivers.PointXYZIT}
   */
  public static final class PointXYZIT extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:apollo.drivers.PointXYZIT)
      PointXYZITOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 1,
        /* suffix= */ "",
        PointXYZIT.class.getName());
    }
    // Use PointXYZIT.newBuilder() to construct.
    private PointXYZIT(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private PointXYZIT() {
      x_ = Float.NaN;
      y_ = Float.NaN;
      z_ = Float.NaN;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return apollo.drivers.Pointcloud.internal_static_apollo_drivers_PointXYZIT_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return apollo.drivers.Pointcloud.internal_static_apollo_drivers_PointXYZIT_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              apollo.drivers.Pointcloud.PointXYZIT.class, apollo.drivers.Pointcloud.PointXYZIT.Builder.class);
    }

    private int bitField0_;
    public static final int X_FIELD_NUMBER = 1;
    private float x_ = Float.NaN;
    /**
     * <code>optional float x = 1 [default = nan];</code>
     * @return Whether the x field is set.
     */
    @java.lang.Override
    public boolean hasX() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional float x = 1 [default = nan];</code>
     * @return The x.
     */
    @java.lang.Override
    public float getX() {
      return x_;
    }

    public static final int Y_FIELD_NUMBER = 2;
    private float y_ = Float.NaN;
    /**
     * <code>optional float y = 2 [default = nan];</code>
     * @return Whether the y field is set.
     */
    @java.lang.Override
    public boolean hasY() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional float y = 2 [default = nan];</code>
     * @return The y.
     */
    @java.lang.Override
    public float getY() {
      return y_;
    }

    public static final int Z_FIELD_NUMBER = 3;
    private float z_ = Float.NaN;
    /**
     * <code>optional float z = 3 [default = nan];</code>
     * @return Whether the z field is set.
     */
    @java.lang.Override
    public boolean hasZ() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional float z = 3 [default = nan];</code>
     * @return The z.
     */
    @java.lang.Override
    public float getZ() {
      return z_;
    }

    public static final int INTENSITY_FIELD_NUMBER = 4;
    private int intensity_ = 0;
    /**
     * <code>optional uint32 intensity = 4 [default = 0];</code>
     * @return Whether the intensity field is set.
     */
    @java.lang.Override
    public boolean hasIntensity() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional uint32 intensity = 4 [default = 0];</code>
     * @return The intensity.
     */
    @java.lang.Override
    public int getIntensity() {
      return intensity_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 5;
    private long timestamp_ = 0L;
    /**
     * <code>optional uint64 timestamp = 5 [default = 0];</code>
     * @return Whether the timestamp field is set.
     */
    @java.lang.Override
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional uint64 timestamp = 5 [default = 0];</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeFloat(1, x_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeFloat(2, y_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeFloat(3, z_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeUInt32(4, intensity_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeUInt64(5, timestamp_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, x_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, y_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, z_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, intensity_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(5, timestamp_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof apollo.drivers.Pointcloud.PointXYZIT)) {
        return super.equals(obj);
      }
      apollo.drivers.Pointcloud.PointXYZIT other = (apollo.drivers.Pointcloud.PointXYZIT) obj;

      if (hasX() != other.hasX()) return false;
      if (hasX()) {
        if (java.lang.Float.floatToIntBits(getX())
            != java.lang.Float.floatToIntBits(
                other.getX())) return false;
      }
      if (hasY() != other.hasY()) return false;
      if (hasY()) {
        if (java.lang.Float.floatToIntBits(getY())
            != java.lang.Float.floatToIntBits(
                other.getY())) return false;
      }
      if (hasZ() != other.hasZ()) return false;
      if (hasZ()) {
        if (java.lang.Float.floatToIntBits(getZ())
            != java.lang.Float.floatToIntBits(
                other.getZ())) return false;
      }
      if (hasIntensity() != other.hasIntensity()) return false;
      if (hasIntensity()) {
        if (getIntensity()
            != other.getIntensity()) return false;
      }
      if (hasTimestamp() != other.hasTimestamp()) return false;
      if (hasTimestamp()) {
        if (getTimestamp()
            != other.getTimestamp()) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasX()) {
        hash = (37 * hash) + X_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getX());
      }
      if (hasY()) {
        hash = (37 * hash) + Y_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getY());
      }
      if (hasZ()) {
        hash = (37 * hash) + Z_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getZ());
      }
      if (hasIntensity()) {
        hash = (37 * hash) + INTENSITY_FIELD_NUMBER;
        hash = (53 * hash) + getIntensity();
      }
      if (hasTimestamp()) {
        hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getTimestamp());
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static apollo.drivers.Pointcloud.PointXYZIT parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static apollo.drivers.Pointcloud.PointXYZIT parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static apollo.drivers.Pointcloud.PointXYZIT parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static apollo.drivers.Pointcloud.PointXYZIT parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static apollo.drivers.Pointcloud.PointXYZIT parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static apollo.drivers.Pointcloud.PointXYZIT parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static apollo.drivers.Pointcloud.PointXYZIT parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static apollo.drivers.Pointcloud.PointXYZIT parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static apollo.drivers.Pointcloud.PointXYZIT parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static apollo.drivers.Pointcloud.PointXYZIT parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static apollo.drivers.Pointcloud.PointXYZIT parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static apollo.drivers.Pointcloud.PointXYZIT parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(apollo.drivers.Pointcloud.PointXYZIT prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code apollo.drivers.PointXYZIT}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:apollo.drivers.PointXYZIT)
        apollo.drivers.Pointcloud.PointXYZITOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return apollo.drivers.Pointcloud.internal_static_apollo_drivers_PointXYZIT_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return apollo.drivers.Pointcloud.internal_static_apollo_drivers_PointXYZIT_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                apollo.drivers.Pointcloud.PointXYZIT.class, apollo.drivers.Pointcloud.PointXYZIT.Builder.class);
      }

      // Construct using apollo.drivers.Pointcloud.PointXYZIT.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        x_ = Float.NaN;
        y_ = Float.NaN;
        z_ = Float.NaN;
        intensity_ = 0;
        timestamp_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return apollo.drivers.Pointcloud.internal_static_apollo_drivers_PointXYZIT_descriptor;
      }

      @java.lang.Override
      public apollo.drivers.Pointcloud.PointXYZIT getDefaultInstanceForType() {
        return apollo.drivers.Pointcloud.PointXYZIT.getDefaultInstance();
      }

      @java.lang.Override
      public apollo.drivers.Pointcloud.PointXYZIT build() {
        apollo.drivers.Pointcloud.PointXYZIT result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public apollo.drivers.Pointcloud.PointXYZIT buildPartial() {
        apollo.drivers.Pointcloud.PointXYZIT result = new apollo.drivers.Pointcloud.PointXYZIT(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(apollo.drivers.Pointcloud.PointXYZIT result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.x_ = x_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.y_ = y_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.z_ = z_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.intensity_ = intensity_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.timestamp_ = timestamp_;
          to_bitField0_ |= 0x00000010;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof apollo.drivers.Pointcloud.PointXYZIT) {
          return mergeFrom((apollo.drivers.Pointcloud.PointXYZIT)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(apollo.drivers.Pointcloud.PointXYZIT other) {
        if (other == apollo.drivers.Pointcloud.PointXYZIT.getDefaultInstance()) return this;
        if (other.hasX()) {
          setX(other.getX());
        }
        if (other.hasY()) {
          setY(other.getY());
        }
        if (other.hasZ()) {
          setZ(other.getZ());
        }
        if (other.hasIntensity()) {
          setIntensity(other.getIntensity());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 13: {
                x_ = input.readFloat();
                bitField0_ |= 0x00000001;
                break;
              } // case 13
              case 21: {
                y_ = input.readFloat();
                bitField0_ |= 0x00000002;
                break;
              } // case 21
              case 29: {
                z_ = input.readFloat();
                bitField0_ |= 0x00000004;
                break;
              } // case 29
              case 32: {
                intensity_ = input.readUInt32();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 40: {
                timestamp_ = input.readUInt64();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private float x_ = Float.NaN;
      /**
       * <code>optional float x = 1 [default = nan];</code>
       * @return Whether the x field is set.
       */
      @java.lang.Override
      public boolean hasX() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional float x = 1 [default = nan];</code>
       * @return The x.
       */
      @java.lang.Override
      public float getX() {
        return x_;
      }
      /**
       * <code>optional float x = 1 [default = nan];</code>
       * @param value The x to set.
       * @return This builder for chaining.
       */
      public Builder setX(float value) {

        x_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional float x = 1 [default = nan];</code>
       * @return This builder for chaining.
       */
      public Builder clearX() {
        bitField0_ = (bitField0_ & ~0x00000001);
        x_ = Float.NaN;
        onChanged();
        return this;
      }

      private float y_ = Float.NaN;
      /**
       * <code>optional float y = 2 [default = nan];</code>
       * @return Whether the y field is set.
       */
      @java.lang.Override
      public boolean hasY() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional float y = 2 [default = nan];</code>
       * @return The y.
       */
      @java.lang.Override
      public float getY() {
        return y_;
      }
      /**
       * <code>optional float y = 2 [default = nan];</code>
       * @param value The y to set.
       * @return This builder for chaining.
       */
      public Builder setY(float value) {

        y_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional float y = 2 [default = nan];</code>
       * @return This builder for chaining.
       */
      public Builder clearY() {
        bitField0_ = (bitField0_ & ~0x00000002);
        y_ = Float.NaN;
        onChanged();
        return this;
      }

      private float z_ = Float.NaN;
      /**
       * <code>optional float z = 3 [default = nan];</code>
       * @return Whether the z field is set.
       */
      @java.lang.Override
      public boolean hasZ() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional float z = 3 [default = nan];</code>
       * @return The z.
       */
      @java.lang.Override
      public float getZ() {
        return z_;
      }
      /**
       * <code>optional float z = 3 [default = nan];</code>
       * @param value The z to set.
       * @return This builder for chaining.
       */
      public Builder setZ(float value) {

        z_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>optional float z = 3 [default = nan];</code>
       * @return This builder for chaining.
       */
      public Builder clearZ() {
        bitField0_ = (bitField0_ & ~0x00000004);
        z_ = Float.NaN;
        onChanged();
        return this;
      }

      private int intensity_ ;
      /**
       * <code>optional uint32 intensity = 4 [default = 0];</code>
       * @return Whether the intensity field is set.
       */
      @java.lang.Override
      public boolean hasIntensity() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional uint32 intensity = 4 [default = 0];</code>
       * @return The intensity.
       */
      @java.lang.Override
      public int getIntensity() {
        return intensity_;
      }
      /**
       * <code>optional uint32 intensity = 4 [default = 0];</code>
       * @param value The intensity to set.
       * @return This builder for chaining.
       */
      public Builder setIntensity(int value) {

        intensity_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 intensity = 4 [default = 0];</code>
       * @return This builder for chaining.
       */
      public Builder clearIntensity() {
        bitField0_ = (bitField0_ & ~0x00000008);
        intensity_ = 0;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>optional uint64 timestamp = 5 [default = 0];</code>
       * @return Whether the timestamp field is set.
       */
      @java.lang.Override
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional uint64 timestamp = 5 [default = 0];</code>
       * @return The timestamp.
       */
      @java.lang.Override
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>optional uint64 timestamp = 5 [default = 0];</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {

        timestamp_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 timestamp = 5 [default = 0];</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000010);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:apollo.drivers.PointXYZIT)
    }

    // @@protoc_insertion_point(class_scope:apollo.drivers.PointXYZIT)
    private static final apollo.drivers.Pointcloud.PointXYZIT DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new apollo.drivers.Pointcloud.PointXYZIT();
    }

    public static apollo.drivers.Pointcloud.PointXYZIT getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PointXYZIT>
        PARSER = new com.google.protobuf.AbstractParser<PointXYZIT>() {
      @java.lang.Override
      public PointXYZIT parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PointXYZIT> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PointXYZIT> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public apollo.drivers.Pointcloud.PointXYZIT getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PointCloudOrBuilder extends
      // @@protoc_insertion_point(interface_extends:apollo.drivers.PointCloud)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .apollo.common.Header header = 1;</code>
     * @return Whether the header field is set.
     */
    boolean hasHeader();
    /**
     * <code>optional .apollo.common.Header header = 1;</code>
     * @return The header.
     */
    apollo.common.HeaderOuterClass.Header getHeader();
    /**
     * <code>optional .apollo.common.Header header = 1;</code>
     */
    apollo.common.HeaderOuterClass.HeaderOrBuilder getHeaderOrBuilder();

    /**
     * <code>optional string frame_id = 2;</code>
     * @return Whether the frameId field is set.
     */
    boolean hasFrameId();
    /**
     * <code>optional string frame_id = 2;</code>
     * @return The frameId.
     */
    java.lang.String getFrameId();
    /**
     * <code>optional string frame_id = 2;</code>
     * @return The bytes for frameId.
     */
    com.google.protobuf.ByteString
        getFrameIdBytes();

    /**
     * <code>optional bool is_dense = 3;</code>
     * @return Whether the isDense field is set.
     */
    boolean hasIsDense();
    /**
     * <code>optional bool is_dense = 3;</code>
     * @return The isDense.
     */
    boolean getIsDense();

    /**
     * <code>repeated .apollo.drivers.PointXYZIT point = 4;</code>
     */
    java.util.List<apollo.drivers.Pointcloud.PointXYZIT> 
        getPointList();
    /**
     * <code>repeated .apollo.drivers.PointXYZIT point = 4;</code>
     */
    apollo.drivers.Pointcloud.PointXYZIT getPoint(int index);
    /**
     * <code>repeated .apollo.drivers.PointXYZIT point = 4;</code>
     */
    int getPointCount();
    /**
     * <code>repeated .apollo.drivers.PointXYZIT point = 4;</code>
     */
    java.util.List<? extends apollo.drivers.Pointcloud.PointXYZITOrBuilder> 
        getPointOrBuilderList();
    /**
     * <code>repeated .apollo.drivers.PointXYZIT point = 4;</code>
     */
    apollo.drivers.Pointcloud.PointXYZITOrBuilder getPointOrBuilder(
        int index);

    /**
     * <code>optional double measurement_time = 5;</code>
     * @return Whether the measurementTime field is set.
     */
    boolean hasMeasurementTime();
    /**
     * <code>optional double measurement_time = 5;</code>
     * @return The measurementTime.
     */
    double getMeasurementTime();

    /**
     * <code>optional uint32 width = 6;</code>
     * @return Whether the width field is set.
     */
    boolean hasWidth();
    /**
     * <code>optional uint32 width = 6;</code>
     * @return The width.
     */
    int getWidth();

    /**
     * <code>optional uint32 height = 7;</code>
     * @return Whether the height field is set.
     */
    boolean hasHeight();
    /**
     * <code>optional uint32 height = 7;</code>
     * @return The height.
     */
    int getHeight();
  }
  /**
   * Protobuf type {@code apollo.drivers.PointCloud}
   */
  public static final class PointCloud extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:apollo.drivers.PointCloud)
      PointCloudOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 1,
        /* suffix= */ "",
        PointCloud.class.getName());
    }
    // Use PointCloud.newBuilder() to construct.
    private PointCloud(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private PointCloud() {
      frameId_ = "";
      point_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return apollo.drivers.Pointcloud.internal_static_apollo_drivers_PointCloud_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return apollo.drivers.Pointcloud.internal_static_apollo_drivers_PointCloud_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              apollo.drivers.Pointcloud.PointCloud.class, apollo.drivers.Pointcloud.PointCloud.Builder.class);
    }

    private int bitField0_;
    public static final int HEADER_FIELD_NUMBER = 1;
    private apollo.common.HeaderOuterClass.Header header_;
    /**
     * <code>optional .apollo.common.Header header = 1;</code>
     * @return Whether the header field is set.
     */
    @java.lang.Override
    public boolean hasHeader() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .apollo.common.Header header = 1;</code>
     * @return The header.
     */
    @java.lang.Override
    public apollo.common.HeaderOuterClass.Header getHeader() {
      return header_ == null ? apollo.common.HeaderOuterClass.Header.getDefaultInstance() : header_;
    }
    /**
     * <code>optional .apollo.common.Header header = 1;</code>
     */
    @java.lang.Override
    public apollo.common.HeaderOuterClass.HeaderOrBuilder getHeaderOrBuilder() {
      return header_ == null ? apollo.common.HeaderOuterClass.Header.getDefaultInstance() : header_;
    }

    public static final int FRAME_ID_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object frameId_ = "";
    /**
     * <code>optional string frame_id = 2;</code>
     * @return Whether the frameId field is set.
     */
    @java.lang.Override
    public boolean hasFrameId() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string frame_id = 2;</code>
     * @return The frameId.
     */
    @java.lang.Override
    public java.lang.String getFrameId() {
      java.lang.Object ref = frameId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          frameId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string frame_id = 2;</code>
     * @return The bytes for frameId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFrameIdBytes() {
      java.lang.Object ref = frameId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        frameId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IS_DENSE_FIELD_NUMBER = 3;
    private boolean isDense_ = false;
    /**
     * <code>optional bool is_dense = 3;</code>
     * @return Whether the isDense field is set.
     */
    @java.lang.Override
    public boolean hasIsDense() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional bool is_dense = 3;</code>
     * @return The isDense.
     */
    @java.lang.Override
    public boolean getIsDense() {
      return isDense_;
    }

    public static final int POINT_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private java.util.List<apollo.drivers.Pointcloud.PointXYZIT> point_;
    /**
     * <code>repeated .apollo.drivers.PointXYZIT point = 4;</code>
     */
    @java.lang.Override
    public java.util.List<apollo.drivers.Pointcloud.PointXYZIT> getPointList() {
      return point_;
    }
    /**
     * <code>repeated .apollo.drivers.PointXYZIT point = 4;</code>
     */
    @java.lang.Override
    public java.util.List<? extends apollo.drivers.Pointcloud.PointXYZITOrBuilder> 
        getPointOrBuilderList() {
      return point_;
    }
    /**
     * <code>repeated .apollo.drivers.PointXYZIT point = 4;</code>
     */
    @java.lang.Override
    public int getPointCount() {
      return point_.size();
    }
    /**
     * <code>repeated .apollo.drivers.PointXYZIT point = 4;</code>
     */
    @java.lang.Override
    public apollo.drivers.Pointcloud.PointXYZIT getPoint(int index) {
      return point_.get(index);
    }
    /**
     * <code>repeated .apollo.drivers.PointXYZIT point = 4;</code>
     */
    @java.lang.Override
    public apollo.drivers.Pointcloud.PointXYZITOrBuilder getPointOrBuilder(
        int index) {
      return point_.get(index);
    }

    public static final int MEASUREMENT_TIME_FIELD_NUMBER = 5;
    private double measurementTime_ = 0D;
    /**
     * <code>optional double measurement_time = 5;</code>
     * @return Whether the measurementTime field is set.
     */
    @java.lang.Override
    public boolean hasMeasurementTime() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional double measurement_time = 5;</code>
     * @return The measurementTime.
     */
    @java.lang.Override
    public double getMeasurementTime() {
      return measurementTime_;
    }

    public static final int WIDTH_FIELD_NUMBER = 6;
    private int width_ = 0;
    /**
     * <code>optional uint32 width = 6;</code>
     * @return Whether the width field is set.
     */
    @java.lang.Override
    public boolean hasWidth() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional uint32 width = 6;</code>
     * @return The width.
     */
    @java.lang.Override
    public int getWidth() {
      return width_;
    }

    public static final int HEIGHT_FIELD_NUMBER = 7;
    private int height_ = 0;
    /**
     * <code>optional uint32 height = 7;</code>
     * @return Whether the height field is set.
     */
    @java.lang.Override
    public boolean hasHeight() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional uint32 height = 7;</code>
     * @return The height.
     */
    @java.lang.Override
    public int getHeight() {
      return height_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getHeader());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, frameId_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeBool(3, isDense_);
      }
      for (int i = 0; i < point_.size(); i++) {
        output.writeMessage(4, point_.get(i));
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeDouble(5, measurementTime_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeUInt32(6, width_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeUInt32(7, height_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getHeader());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, frameId_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, isDense_);
      }
      for (int i = 0; i < point_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, point_.get(i));
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, measurementTime_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(6, width_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(7, height_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof apollo.drivers.Pointcloud.PointCloud)) {
        return super.equals(obj);
      }
      apollo.drivers.Pointcloud.PointCloud other = (apollo.drivers.Pointcloud.PointCloud) obj;

      if (hasHeader() != other.hasHeader()) return false;
      if (hasHeader()) {
        if (!getHeader()
            .equals(other.getHeader())) return false;
      }
      if (hasFrameId() != other.hasFrameId()) return false;
      if (hasFrameId()) {
        if (!getFrameId()
            .equals(other.getFrameId())) return false;
      }
      if (hasIsDense() != other.hasIsDense()) return false;
      if (hasIsDense()) {
        if (getIsDense()
            != other.getIsDense()) return false;
      }
      if (!getPointList()
          .equals(other.getPointList())) return false;
      if (hasMeasurementTime() != other.hasMeasurementTime()) return false;
      if (hasMeasurementTime()) {
        if (java.lang.Double.doubleToLongBits(getMeasurementTime())
            != java.lang.Double.doubleToLongBits(
                other.getMeasurementTime())) return false;
      }
      if (hasWidth() != other.hasWidth()) return false;
      if (hasWidth()) {
        if (getWidth()
            != other.getWidth()) return false;
      }
      if (hasHeight() != other.hasHeight()) return false;
      if (hasHeight()) {
        if (getHeight()
            != other.getHeight()) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasHeader()) {
        hash = (37 * hash) + HEADER_FIELD_NUMBER;
        hash = (53 * hash) + getHeader().hashCode();
      }
      if (hasFrameId()) {
        hash = (37 * hash) + FRAME_ID_FIELD_NUMBER;
        hash = (53 * hash) + getFrameId().hashCode();
      }
      if (hasIsDense()) {
        hash = (37 * hash) + IS_DENSE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getIsDense());
      }
      if (getPointCount() > 0) {
        hash = (37 * hash) + POINT_FIELD_NUMBER;
        hash = (53 * hash) + getPointList().hashCode();
      }
      if (hasMeasurementTime()) {
        hash = (37 * hash) + MEASUREMENT_TIME_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getMeasurementTime()));
      }
      if (hasWidth()) {
        hash = (37 * hash) + WIDTH_FIELD_NUMBER;
        hash = (53 * hash) + getWidth();
      }
      if (hasHeight()) {
        hash = (37 * hash) + HEIGHT_FIELD_NUMBER;
        hash = (53 * hash) + getHeight();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static apollo.drivers.Pointcloud.PointCloud parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static apollo.drivers.Pointcloud.PointCloud parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static apollo.drivers.Pointcloud.PointCloud parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static apollo.drivers.Pointcloud.PointCloud parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static apollo.drivers.Pointcloud.PointCloud parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static apollo.drivers.Pointcloud.PointCloud parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static apollo.drivers.Pointcloud.PointCloud parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static apollo.drivers.Pointcloud.PointCloud parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static apollo.drivers.Pointcloud.PointCloud parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static apollo.drivers.Pointcloud.PointCloud parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static apollo.drivers.Pointcloud.PointCloud parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static apollo.drivers.Pointcloud.PointCloud parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(apollo.drivers.Pointcloud.PointCloud prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code apollo.drivers.PointCloud}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:apollo.drivers.PointCloud)
        apollo.drivers.Pointcloud.PointCloudOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return apollo.drivers.Pointcloud.internal_static_apollo_drivers_PointCloud_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return apollo.drivers.Pointcloud.internal_static_apollo_drivers_PointCloud_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                apollo.drivers.Pointcloud.PointCloud.class, apollo.drivers.Pointcloud.PointCloud.Builder.class);
      }

      // Construct using apollo.drivers.Pointcloud.PointCloud.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          getHeaderFieldBuilder();
          getPointFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        header_ = null;
        if (headerBuilder_ != null) {
          headerBuilder_.dispose();
          headerBuilder_ = null;
        }
        frameId_ = "";
        isDense_ = false;
        if (pointBuilder_ == null) {
          point_ = java.util.Collections.emptyList();
        } else {
          point_ = null;
          pointBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        measurementTime_ = 0D;
        width_ = 0;
        height_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return apollo.drivers.Pointcloud.internal_static_apollo_drivers_PointCloud_descriptor;
      }

      @java.lang.Override
      public apollo.drivers.Pointcloud.PointCloud getDefaultInstanceForType() {
        return apollo.drivers.Pointcloud.PointCloud.getDefaultInstance();
      }

      @java.lang.Override
      public apollo.drivers.Pointcloud.PointCloud build() {
        apollo.drivers.Pointcloud.PointCloud result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public apollo.drivers.Pointcloud.PointCloud buildPartial() {
        apollo.drivers.Pointcloud.PointCloud result = new apollo.drivers.Pointcloud.PointCloud(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(apollo.drivers.Pointcloud.PointCloud result) {
        if (pointBuilder_ == null) {
          if (((bitField0_ & 0x00000008) != 0)) {
            point_ = java.util.Collections.unmodifiableList(point_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.point_ = point_;
        } else {
          result.point_ = pointBuilder_.build();
        }
      }

      private void buildPartial0(apollo.drivers.Pointcloud.PointCloud result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.header_ = headerBuilder_ == null
              ? header_
              : headerBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.frameId_ = frameId_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.isDense_ = isDense_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.measurementTime_ = measurementTime_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.width_ = width_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.height_ = height_;
          to_bitField0_ |= 0x00000020;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof apollo.drivers.Pointcloud.PointCloud) {
          return mergeFrom((apollo.drivers.Pointcloud.PointCloud)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(apollo.drivers.Pointcloud.PointCloud other) {
        if (other == apollo.drivers.Pointcloud.PointCloud.getDefaultInstance()) return this;
        if (other.hasHeader()) {
          mergeHeader(other.getHeader());
        }
        if (other.hasFrameId()) {
          frameId_ = other.frameId_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.hasIsDense()) {
          setIsDense(other.getIsDense());
        }
        if (pointBuilder_ == null) {
          if (!other.point_.isEmpty()) {
            if (point_.isEmpty()) {
              point_ = other.point_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensurePointIsMutable();
              point_.addAll(other.point_);
            }
            onChanged();
          }
        } else {
          if (!other.point_.isEmpty()) {
            if (pointBuilder_.isEmpty()) {
              pointBuilder_.dispose();
              pointBuilder_ = null;
              point_ = other.point_;
              bitField0_ = (bitField0_ & ~0x00000008);
              pointBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPointFieldBuilder() : null;
            } else {
              pointBuilder_.addAllMessages(other.point_);
            }
          }
        }
        if (other.hasMeasurementTime()) {
          setMeasurementTime(other.getMeasurementTime());
        }
        if (other.hasWidth()) {
          setWidth(other.getWidth());
        }
        if (other.hasHeight()) {
          setHeight(other.getHeight());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getHeaderFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                frameId_ = input.readBytes();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                isDense_ = input.readBool();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 34: {
                apollo.drivers.Pointcloud.PointXYZIT m =
                    input.readMessage(
                        apollo.drivers.Pointcloud.PointXYZIT.parser(),
                        extensionRegistry);
                if (pointBuilder_ == null) {
                  ensurePointIsMutable();
                  point_.add(m);
                } else {
                  pointBuilder_.addMessage(m);
                }
                break;
              } // case 34
              case 41: {
                measurementTime_ = input.readDouble();
                bitField0_ |= 0x00000010;
                break;
              } // case 41
              case 48: {
                width_ = input.readUInt32();
                bitField0_ |= 0x00000020;
                break;
              } // case 48
              case 56: {
                height_ = input.readUInt32();
                bitField0_ |= 0x00000040;
                break;
              } // case 56
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private apollo.common.HeaderOuterClass.Header header_;
      private com.google.protobuf.SingleFieldBuilder<
          apollo.common.HeaderOuterClass.Header, apollo.common.HeaderOuterClass.Header.Builder, apollo.common.HeaderOuterClass.HeaderOrBuilder> headerBuilder_;
      /**
       * <code>optional .apollo.common.Header header = 1;</code>
       * @return Whether the header field is set.
       */
      public boolean hasHeader() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional .apollo.common.Header header = 1;</code>
       * @return The header.
       */
      public apollo.common.HeaderOuterClass.Header getHeader() {
        if (headerBuilder_ == null) {
          return header_ == null ? apollo.common.HeaderOuterClass.Header.getDefaultInstance() : header_;
        } else {
          return headerBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .apollo.common.Header header = 1;</code>
       */
      public Builder setHeader(apollo.common.HeaderOuterClass.Header value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          header_ = value;
        } else {
          headerBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional .apollo.common.Header header = 1;</code>
       */
      public Builder setHeader(
          apollo.common.HeaderOuterClass.Header.Builder builderForValue) {
        if (headerBuilder_ == null) {
          header_ = builderForValue.build();
        } else {
          headerBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional .apollo.common.Header header = 1;</code>
       */
      public Builder mergeHeader(apollo.common.HeaderOuterClass.Header value) {
        if (headerBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            header_ != null &&
            header_ != apollo.common.HeaderOuterClass.Header.getDefaultInstance()) {
            getHeaderBuilder().mergeFrom(value);
          } else {
            header_ = value;
          }
        } else {
          headerBuilder_.mergeFrom(value);
        }
        if (header_ != null) {
          bitField0_ |= 0x00000001;
          onChanged();
        }
        return this;
      }
      /**
       * <code>optional .apollo.common.Header header = 1;</code>
       */
      public Builder clearHeader() {
        bitField0_ = (bitField0_ & ~0x00000001);
        header_ = null;
        if (headerBuilder_ != null) {
          headerBuilder_.dispose();
          headerBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>optional .apollo.common.Header header = 1;</code>
       */
      public apollo.common.HeaderOuterClass.Header.Builder getHeaderBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getHeaderFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .apollo.common.Header header = 1;</code>
       */
      public apollo.common.HeaderOuterClass.HeaderOrBuilder getHeaderOrBuilder() {
        if (headerBuilder_ != null) {
          return headerBuilder_.getMessageOrBuilder();
        } else {
          return header_ == null ?
              apollo.common.HeaderOuterClass.Header.getDefaultInstance() : header_;
        }
      }
      /**
       * <code>optional .apollo.common.Header header = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          apollo.common.HeaderOuterClass.Header, apollo.common.HeaderOuterClass.Header.Builder, apollo.common.HeaderOuterClass.HeaderOrBuilder> 
          getHeaderFieldBuilder() {
        if (headerBuilder_ == null) {
          headerBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              apollo.common.HeaderOuterClass.Header, apollo.common.HeaderOuterClass.Header.Builder, apollo.common.HeaderOuterClass.HeaderOrBuilder>(
                  getHeader(),
                  getParentForChildren(),
                  isClean());
          header_ = null;
        }
        return headerBuilder_;
      }

      private java.lang.Object frameId_ = "";
      /**
       * <code>optional string frame_id = 2;</code>
       * @return Whether the frameId field is set.
       */
      public boolean hasFrameId() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string frame_id = 2;</code>
       * @return The frameId.
       */
      public java.lang.String getFrameId() {
        java.lang.Object ref = frameId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            frameId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string frame_id = 2;</code>
       * @return The bytes for frameId.
       */
      public com.google.protobuf.ByteString
          getFrameIdBytes() {
        java.lang.Object ref = frameId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          frameId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string frame_id = 2;</code>
       * @param value The frameId to set.
       * @return This builder for chaining.
       */
      public Builder setFrameId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        frameId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional string frame_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFrameId() {
        frameId_ = getDefaultInstance().getFrameId();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>optional string frame_id = 2;</code>
       * @param value The bytes for frameId to set.
       * @return This builder for chaining.
       */
      public Builder setFrameIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        frameId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private boolean isDense_ ;
      /**
       * <code>optional bool is_dense = 3;</code>
       * @return Whether the isDense field is set.
       */
      @java.lang.Override
      public boolean hasIsDense() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional bool is_dense = 3;</code>
       * @return The isDense.
       */
      @java.lang.Override
      public boolean getIsDense() {
        return isDense_;
      }
      /**
       * <code>optional bool is_dense = 3;</code>
       * @param value The isDense to set.
       * @return This builder for chaining.
       */
      public Builder setIsDense(boolean value) {

        isDense_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool is_dense = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsDense() {
        bitField0_ = (bitField0_ & ~0x00000004);
        isDense_ = false;
        onChanged();
        return this;
      }

      private java.util.List<apollo.drivers.Pointcloud.PointXYZIT> point_ =
        java.util.Collections.emptyList();
      private void ensurePointIsMutable() {
        if (!((bitField0_ & 0x00000008) != 0)) {
          point_ = new java.util.ArrayList<apollo.drivers.Pointcloud.PointXYZIT>(point_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          apollo.drivers.Pointcloud.PointXYZIT, apollo.drivers.Pointcloud.PointXYZIT.Builder, apollo.drivers.Pointcloud.PointXYZITOrBuilder> pointBuilder_;

      /**
       * <code>repeated .apollo.drivers.PointXYZIT point = 4;</code>
       */
      public java.util.List<apollo.drivers.Pointcloud.PointXYZIT> getPointList() {
        if (pointBuilder_ == null) {
          return java.util.Collections.unmodifiableList(point_);
        } else {
          return pointBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .apollo.drivers.PointXYZIT point = 4;</code>
       */
      public int getPointCount() {
        if (pointBuilder_ == null) {
          return point_.size();
        } else {
          return pointBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .apollo.drivers.PointXYZIT point = 4;</code>
       */
      public apollo.drivers.Pointcloud.PointXYZIT getPoint(int index) {
        if (pointBuilder_ == null) {
          return point_.get(index);
        } else {
          return pointBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .apollo.drivers.PointXYZIT point = 4;</code>
       */
      public Builder setPoint(
          int index, apollo.drivers.Pointcloud.PointXYZIT value) {
        if (pointBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePointIsMutable();
          point_.set(index, value);
          onChanged();
        } else {
          pointBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .apollo.drivers.PointXYZIT point = 4;</code>
       */
      public Builder setPoint(
          int index, apollo.drivers.Pointcloud.PointXYZIT.Builder builderForValue) {
        if (pointBuilder_ == null) {
          ensurePointIsMutable();
          point_.set(index, builderForValue.build());
          onChanged();
        } else {
          pointBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .apollo.drivers.PointXYZIT point = 4;</code>
       */
      public Builder addPoint(apollo.drivers.Pointcloud.PointXYZIT value) {
        if (pointBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePointIsMutable();
          point_.add(value);
          onChanged();
        } else {
          pointBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .apollo.drivers.PointXYZIT point = 4;</code>
       */
      public Builder addPoint(
          int index, apollo.drivers.Pointcloud.PointXYZIT value) {
        if (pointBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePointIsMutable();
          point_.add(index, value);
          onChanged();
        } else {
          pointBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .apollo.drivers.PointXYZIT point = 4;</code>
       */
      public Builder addPoint(
          apollo.drivers.Pointcloud.PointXYZIT.Builder builderForValue) {
        if (pointBuilder_ == null) {
          ensurePointIsMutable();
          point_.add(builderForValue.build());
          onChanged();
        } else {
          pointBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .apollo.drivers.PointXYZIT point = 4;</code>
       */
      public Builder addPoint(
          int index, apollo.drivers.Pointcloud.PointXYZIT.Builder builderForValue) {
        if (pointBuilder_ == null) {
          ensurePointIsMutable();
          point_.add(index, builderForValue.build());
          onChanged();
        } else {
          pointBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .apollo.drivers.PointXYZIT point = 4;</code>
       */
      public Builder addAllPoint(
          java.lang.Iterable<? extends apollo.drivers.Pointcloud.PointXYZIT> values) {
        if (pointBuilder_ == null) {
          ensurePointIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, point_);
          onChanged();
        } else {
          pointBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .apollo.drivers.PointXYZIT point = 4;</code>
       */
      public Builder clearPoint() {
        if (pointBuilder_ == null) {
          point_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          pointBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .apollo.drivers.PointXYZIT point = 4;</code>
       */
      public Builder removePoint(int index) {
        if (pointBuilder_ == null) {
          ensurePointIsMutable();
          point_.remove(index);
          onChanged();
        } else {
          pointBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .apollo.drivers.PointXYZIT point = 4;</code>
       */
      public apollo.drivers.Pointcloud.PointXYZIT.Builder getPointBuilder(
          int index) {
        return getPointFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .apollo.drivers.PointXYZIT point = 4;</code>
       */
      public apollo.drivers.Pointcloud.PointXYZITOrBuilder getPointOrBuilder(
          int index) {
        if (pointBuilder_ == null) {
          return point_.get(index);  } else {
          return pointBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .apollo.drivers.PointXYZIT point = 4;</code>
       */
      public java.util.List<? extends apollo.drivers.Pointcloud.PointXYZITOrBuilder> 
           getPointOrBuilderList() {
        if (pointBuilder_ != null) {
          return pointBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(point_);
        }
      }
      /**
       * <code>repeated .apollo.drivers.PointXYZIT point = 4;</code>
       */
      public apollo.drivers.Pointcloud.PointXYZIT.Builder addPointBuilder() {
        return getPointFieldBuilder().addBuilder(
            apollo.drivers.Pointcloud.PointXYZIT.getDefaultInstance());
      }
      /**
       * <code>repeated .apollo.drivers.PointXYZIT point = 4;</code>
       */
      public apollo.drivers.Pointcloud.PointXYZIT.Builder addPointBuilder(
          int index) {
        return getPointFieldBuilder().addBuilder(
            index, apollo.drivers.Pointcloud.PointXYZIT.getDefaultInstance());
      }
      /**
       * <code>repeated .apollo.drivers.PointXYZIT point = 4;</code>
       */
      public java.util.List<apollo.drivers.Pointcloud.PointXYZIT.Builder> 
           getPointBuilderList() {
        return getPointFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          apollo.drivers.Pointcloud.PointXYZIT, apollo.drivers.Pointcloud.PointXYZIT.Builder, apollo.drivers.Pointcloud.PointXYZITOrBuilder> 
          getPointFieldBuilder() {
        if (pointBuilder_ == null) {
          pointBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              apollo.drivers.Pointcloud.PointXYZIT, apollo.drivers.Pointcloud.PointXYZIT.Builder, apollo.drivers.Pointcloud.PointXYZITOrBuilder>(
                  point_,
                  ((bitField0_ & 0x00000008) != 0),
                  getParentForChildren(),
                  isClean());
          point_ = null;
        }
        return pointBuilder_;
      }

      private double measurementTime_ ;
      /**
       * <code>optional double measurement_time = 5;</code>
       * @return Whether the measurementTime field is set.
       */
      @java.lang.Override
      public boolean hasMeasurementTime() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional double measurement_time = 5;</code>
       * @return The measurementTime.
       */
      @java.lang.Override
      public double getMeasurementTime() {
        return measurementTime_;
      }
      /**
       * <code>optional double measurement_time = 5;</code>
       * @param value The measurementTime to set.
       * @return This builder for chaining.
       */
      public Builder setMeasurementTime(double value) {

        measurementTime_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>optional double measurement_time = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearMeasurementTime() {
        bitField0_ = (bitField0_ & ~0x00000010);
        measurementTime_ = 0D;
        onChanged();
        return this;
      }

      private int width_ ;
      /**
       * <code>optional uint32 width = 6;</code>
       * @return Whether the width field is set.
       */
      @java.lang.Override
      public boolean hasWidth() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>optional uint32 width = 6;</code>
       * @return The width.
       */
      @java.lang.Override
      public int getWidth() {
        return width_;
      }
      /**
       * <code>optional uint32 width = 6;</code>
       * @param value The width to set.
       * @return This builder for chaining.
       */
      public Builder setWidth(int value) {

        width_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 width = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearWidth() {
        bitField0_ = (bitField0_ & ~0x00000020);
        width_ = 0;
        onChanged();
        return this;
      }

      private int height_ ;
      /**
       * <code>optional uint32 height = 7;</code>
       * @return Whether the height field is set.
       */
      @java.lang.Override
      public boolean hasHeight() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <code>optional uint32 height = 7;</code>
       * @return The height.
       */
      @java.lang.Override
      public int getHeight() {
        return height_;
      }
      /**
       * <code>optional uint32 height = 7;</code>
       * @param value The height to set.
       * @return This builder for chaining.
       */
      public Builder setHeight(int value) {

        height_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 height = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearHeight() {
        bitField0_ = (bitField0_ & ~0x00000040);
        height_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:apollo.drivers.PointCloud)
    }

    // @@protoc_insertion_point(class_scope:apollo.drivers.PointCloud)
    private static final apollo.drivers.Pointcloud.PointCloud DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new apollo.drivers.Pointcloud.PointCloud();
    }

    public static apollo.drivers.Pointcloud.PointCloud getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PointCloud>
        PARSER = new com.google.protobuf.AbstractParser<PointCloud>() {
      @java.lang.Override
      public PointCloud parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PointCloud> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PointCloud> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public apollo.drivers.Pointcloud.PointCloud getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apollo_drivers_PointXYZIT_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_apollo_drivers_PointXYZIT_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apollo_drivers_PointCloud_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_apollo_drivers_PointCloud_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n&modules/drivers/proto/pointcloud.proto" +
      "\022\016apollo.drivers\032!modules/common/proto/h" +
      "eader.proto\"h\n\nPointXYZIT\022\016\n\001x\030\001 \001(\002:\003na" +
      "n\022\016\n\001y\030\002 \001(\002:\003nan\022\016\n\001z\030\003 \001(\002:\003nan\022\024\n\tint" +
      "ensity\030\004 \001(\r:\0010\022\024\n\ttimestamp\030\005 \001(\004:\0010\"\273\001" +
      "\n\nPointCloud\022%\n\006header\030\001 \001(\0132\025.apollo.co" +
      "mmon.Header\022\020\n\010frame_id\030\002 \001(\t\022\020\n\010is_dens" +
      "e\030\003 \001(\010\022)\n\005point\030\004 \003(\0132\032.apollo.drivers." +
      "PointXYZIT\022\030\n\020measurement_time\030\005 \001(\001\022\r\n\005" +
      "width\030\006 \001(\r\022\016\n\006height\030\007 \001(\r"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          apollo.common.HeaderOuterClass.getDescriptor(),
        });
    internal_static_apollo_drivers_PointXYZIT_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_apollo_drivers_PointXYZIT_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_apollo_drivers_PointXYZIT_descriptor,
        new java.lang.String[] { "X", "Y", "Z", "Intensity", "Timestamp", });
    internal_static_apollo_drivers_PointCloud_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_apollo_drivers_PointCloud_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_apollo_drivers_PointCloud_descriptor,
        new java.lang.String[] { "Header", "FrameId", "IsDense", "Point", "MeasurementTime", "Width", "Height", });
    descriptor.resolveAllFeaturesImmutable();
    apollo.common.HeaderOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
