
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/antique/clion-2023.3.2/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 6.5.0-21-generic - x86_64
...
