// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/common/proto/drive_state.proto
// Protobuf Java Version: 4.26.1

package apollo.common;

public final class DriveState {
  private DriveState() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      DriveState.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EngageAdviceOrBuilder extends
      // @@protoc_insertion_point(interface_extends:apollo.common.EngageAdvice)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .apollo.common.EngageAdvice.Advice advice = 1 [default = DISALLOW_ENGAGE];</code>
     * @return Whether the advice field is set.
     */
    boolean hasAdvice();
    /**
     * <code>optional .apollo.common.EngageAdvice.Advice advice = 1 [default = DISALLOW_ENGAGE];</code>
     * @return The advice.
     */
    apollo.common.DriveState.EngageAdvice.Advice getAdvice();

    /**
     * <code>optional string reason = 2;</code>
     * @return Whether the reason field is set.
     */
    boolean hasReason();
    /**
     * <code>optional string reason = 2;</code>
     * @return The reason.
     */
    java.lang.String getReason();
    /**
     * <code>optional string reason = 2;</code>
     * @return The bytes for reason.
     */
    com.google.protobuf.ByteString
        getReasonBytes();
  }
  /**
   * <pre>
   * This is the engage advice that published by critical runtime modules.
   * </pre>
   *
   * Protobuf type {@code apollo.common.EngageAdvice}
   */
  public static final class EngageAdvice extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:apollo.common.EngageAdvice)
      EngageAdviceOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 1,
        /* suffix= */ "",
        EngageAdvice.class.getName());
    }
    // Use EngageAdvice.newBuilder() to construct.
    private EngageAdvice(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private EngageAdvice() {
      advice_ = 1;
      reason_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return apollo.common.DriveState.internal_static_apollo_common_EngageAdvice_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return apollo.common.DriveState.internal_static_apollo_common_EngageAdvice_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              apollo.common.DriveState.EngageAdvice.class, apollo.common.DriveState.EngageAdvice.Builder.class);
    }

    /**
     * Protobuf enum {@code apollo.common.EngageAdvice.Advice}
     */
    public enum Advice
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>UNKNOWN = 0;</code>
       */
      UNKNOWN(0),
      /**
       * <code>DISALLOW_ENGAGE = 1;</code>
       */
      DISALLOW_ENGAGE(1),
      /**
       * <code>READY_TO_ENGAGE = 2;</code>
       */
      READY_TO_ENGAGE(2),
      /**
       * <code>KEEP_ENGAGED = 3;</code>
       */
      KEEP_ENGAGED(3),
      /**
       * <code>PREPARE_DISENGAGE = 4;</code>
       */
      PREPARE_DISENGAGE(4),
      ;

      static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
          com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
          /* major= */ 4,
          /* minor= */ 26,
          /* patch= */ 1,
          /* suffix= */ "",
          Advice.class.getName());
      }
      /**
       * <code>UNKNOWN = 0;</code>
       */
      public static final int UNKNOWN_VALUE = 0;
      /**
       * <code>DISALLOW_ENGAGE = 1;</code>
       */
      public static final int DISALLOW_ENGAGE_VALUE = 1;
      /**
       * <code>READY_TO_ENGAGE = 2;</code>
       */
      public static final int READY_TO_ENGAGE_VALUE = 2;
      /**
       * <code>KEEP_ENGAGED = 3;</code>
       */
      public static final int KEEP_ENGAGED_VALUE = 3;
      /**
       * <code>PREPARE_DISENGAGE = 4;</code>
       */
      public static final int PREPARE_DISENGAGE_VALUE = 4;


      public final int getNumber() {
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Advice valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Advice forNumber(int value) {
        switch (value) {
          case 0: return UNKNOWN;
          case 1: return DISALLOW_ENGAGE;
          case 2: return READY_TO_ENGAGE;
          case 3: return KEEP_ENGAGED;
          case 4: return PREPARE_DISENGAGE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Advice>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Advice> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Advice>() {
              public Advice findValueByNumber(int number) {
                return Advice.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return apollo.common.DriveState.EngageAdvice.getDescriptor().getEnumTypes().get(0);
      }

      private static final Advice[] VALUES = values();

      public static Advice valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Advice(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:apollo.common.EngageAdvice.Advice)
    }

    private int bitField0_;
    public static final int ADVICE_FIELD_NUMBER = 1;
    private int advice_ = 1;
    /**
     * <code>optional .apollo.common.EngageAdvice.Advice advice = 1 [default = DISALLOW_ENGAGE];</code>
     * @return Whether the advice field is set.
     */
    @java.lang.Override public boolean hasAdvice() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .apollo.common.EngageAdvice.Advice advice = 1 [default = DISALLOW_ENGAGE];</code>
     * @return The advice.
     */
    @java.lang.Override public apollo.common.DriveState.EngageAdvice.Advice getAdvice() {
      apollo.common.DriveState.EngageAdvice.Advice result = apollo.common.DriveState.EngageAdvice.Advice.forNumber(advice_);
      return result == null ? apollo.common.DriveState.EngageAdvice.Advice.DISALLOW_ENGAGE : result;
    }

    public static final int REASON_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object reason_ = "";
    /**
     * <code>optional string reason = 2;</code>
     * @return Whether the reason field is set.
     */
    @java.lang.Override
    public boolean hasReason() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string reason = 2;</code>
     * @return The reason.
     */
    @java.lang.Override
    public java.lang.String getReason() {
      java.lang.Object ref = reason_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          reason_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string reason = 2;</code>
     * @return The bytes for reason.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getReasonBytes() {
      java.lang.Object ref = reason_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reason_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeEnum(1, advice_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, reason_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, advice_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, reason_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof apollo.common.DriveState.EngageAdvice)) {
        return super.equals(obj);
      }
      apollo.common.DriveState.EngageAdvice other = (apollo.common.DriveState.EngageAdvice) obj;

      if (hasAdvice() != other.hasAdvice()) return false;
      if (hasAdvice()) {
        if (advice_ != other.advice_) return false;
      }
      if (hasReason() != other.hasReason()) return false;
      if (hasReason()) {
        if (!getReason()
            .equals(other.getReason())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasAdvice()) {
        hash = (37 * hash) + ADVICE_FIELD_NUMBER;
        hash = (53 * hash) + advice_;
      }
      if (hasReason()) {
        hash = (37 * hash) + REASON_FIELD_NUMBER;
        hash = (53 * hash) + getReason().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static apollo.common.DriveState.EngageAdvice parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static apollo.common.DriveState.EngageAdvice parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static apollo.common.DriveState.EngageAdvice parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static apollo.common.DriveState.EngageAdvice parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static apollo.common.DriveState.EngageAdvice parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static apollo.common.DriveState.EngageAdvice parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static apollo.common.DriveState.EngageAdvice parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static apollo.common.DriveState.EngageAdvice parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static apollo.common.DriveState.EngageAdvice parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static apollo.common.DriveState.EngageAdvice parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static apollo.common.DriveState.EngageAdvice parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static apollo.common.DriveState.EngageAdvice parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(apollo.common.DriveState.EngageAdvice prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * This is the engage advice that published by critical runtime modules.
     * </pre>
     *
     * Protobuf type {@code apollo.common.EngageAdvice}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:apollo.common.EngageAdvice)
        apollo.common.DriveState.EngageAdviceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return apollo.common.DriveState.internal_static_apollo_common_EngageAdvice_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return apollo.common.DriveState.internal_static_apollo_common_EngageAdvice_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                apollo.common.DriveState.EngageAdvice.class, apollo.common.DriveState.EngageAdvice.Builder.class);
      }

      // Construct using apollo.common.DriveState.EngageAdvice.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        advice_ = 1;
        reason_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return apollo.common.DriveState.internal_static_apollo_common_EngageAdvice_descriptor;
      }

      @java.lang.Override
      public apollo.common.DriveState.EngageAdvice getDefaultInstanceForType() {
        return apollo.common.DriveState.EngageAdvice.getDefaultInstance();
      }

      @java.lang.Override
      public apollo.common.DriveState.EngageAdvice build() {
        apollo.common.DriveState.EngageAdvice result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public apollo.common.DriveState.EngageAdvice buildPartial() {
        apollo.common.DriveState.EngageAdvice result = new apollo.common.DriveState.EngageAdvice(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(apollo.common.DriveState.EngageAdvice result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.advice_ = advice_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.reason_ = reason_;
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof apollo.common.DriveState.EngageAdvice) {
          return mergeFrom((apollo.common.DriveState.EngageAdvice)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(apollo.common.DriveState.EngageAdvice other) {
        if (other == apollo.common.DriveState.EngageAdvice.getDefaultInstance()) return this;
        if (other.hasAdvice()) {
          setAdvice(other.getAdvice());
        }
        if (other.hasReason()) {
          reason_ = other.reason_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                int tmpRaw = input.readEnum();
                apollo.common.DriveState.EngageAdvice.Advice tmpValue =
                    apollo.common.DriveState.EngageAdvice.Advice.forNumber(tmpRaw);
                if (tmpValue == null) {
                  mergeUnknownVarintField(1, tmpRaw);
                } else {
                  advice_ = tmpRaw;
                  bitField0_ |= 0x00000001;
                }
                break;
              } // case 8
              case 18: {
                reason_ = input.readBytes();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int advice_ = 1;
      /**
       * <code>optional .apollo.common.EngageAdvice.Advice advice = 1 [default = DISALLOW_ENGAGE];</code>
       * @return Whether the advice field is set.
       */
      @java.lang.Override public boolean hasAdvice() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional .apollo.common.EngageAdvice.Advice advice = 1 [default = DISALLOW_ENGAGE];</code>
       * @return The advice.
       */
      @java.lang.Override
      public apollo.common.DriveState.EngageAdvice.Advice getAdvice() {
        apollo.common.DriveState.EngageAdvice.Advice result = apollo.common.DriveState.EngageAdvice.Advice.forNumber(advice_);
        return result == null ? apollo.common.DriveState.EngageAdvice.Advice.DISALLOW_ENGAGE : result;
      }
      /**
       * <code>optional .apollo.common.EngageAdvice.Advice advice = 1 [default = DISALLOW_ENGAGE];</code>
       * @param value The advice to set.
       * @return This builder for chaining.
       */
      public Builder setAdvice(apollo.common.DriveState.EngageAdvice.Advice value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        advice_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .apollo.common.EngageAdvice.Advice advice = 1 [default = DISALLOW_ENGAGE];</code>
       * @return This builder for chaining.
       */
      public Builder clearAdvice() {
        bitField0_ = (bitField0_ & ~0x00000001);
        advice_ = 1;
        onChanged();
        return this;
      }

      private java.lang.Object reason_ = "";
      /**
       * <code>optional string reason = 2;</code>
       * @return Whether the reason field is set.
       */
      public boolean hasReason() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string reason = 2;</code>
       * @return The reason.
       */
      public java.lang.String getReason() {
        java.lang.Object ref = reason_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            reason_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string reason = 2;</code>
       * @return The bytes for reason.
       */
      public com.google.protobuf.ByteString
          getReasonBytes() {
        java.lang.Object ref = reason_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          reason_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string reason = 2;</code>
       * @param value The reason to set.
       * @return This builder for chaining.
       */
      public Builder setReason(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        reason_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional string reason = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearReason() {
        reason_ = getDefaultInstance().getReason();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>optional string reason = 2;</code>
       * @param value The bytes for reason to set.
       * @return This builder for chaining.
       */
      public Builder setReasonBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        reason_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:apollo.common.EngageAdvice)
    }

    // @@protoc_insertion_point(class_scope:apollo.common.EngageAdvice)
    private static final apollo.common.DriveState.EngageAdvice DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new apollo.common.DriveState.EngageAdvice();
    }

    public static apollo.common.DriveState.EngageAdvice getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EngageAdvice>
        PARSER = new com.google.protobuf.AbstractParser<EngageAdvice>() {
      @java.lang.Override
      public EngageAdvice parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<EngageAdvice> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EngageAdvice> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public apollo.common.DriveState.EngageAdvice getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apollo_common_EngageAdvice_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_apollo_common_EngageAdvice_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n&modules/common/proto/drive_state.proto" +
      "\022\rapollo.common\"\315\001\n\014EngageAdvice\022C\n\006advi" +
      "ce\030\001 \001(\0162\".apollo.common.EngageAdvice.Ad" +
      "vice:\017DISALLOW_ENGAGE\022\016\n\006reason\030\002 \001(\t\"h\n" +
      "\006Advice\022\013\n\007UNKNOWN\020\000\022\023\n\017DISALLOW_ENGAGE\020" +
      "\001\022\023\n\017READY_TO_ENGAGE\020\002\022\020\n\014KEEP_ENGAGED\020\003" +
      "\022\025\n\021PREPARE_DISENGAGE\020\004"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_apollo_common_EngageAdvice_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_apollo_common_EngageAdvice_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_apollo_common_EngageAdvice_descriptor,
        new java.lang.String[] { "Advice", "Reason", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
