// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/common/proto/drive_event.proto
// Protobuf Java Version: 4.26.1

package apollo.common;

public final class DriveEventOuterClass {
  private DriveEventOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      DriveEventOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DriveEventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:apollo.common.DriveEvent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .apollo.common.Header header = 1;</code>
     * @return Whether the header field is set.
     */
    boolean hasHeader();
    /**
     * <code>optional .apollo.common.Header header = 1;</code>
     * @return The header.
     */
    apollo.common.HeaderOuterClass.Header getHeader();
    /**
     * <code>optional .apollo.common.Header header = 1;</code>
     */
    apollo.common.HeaderOuterClass.HeaderOrBuilder getHeaderOrBuilder();

    /**
     * <code>optional string event = 2;</code>
     * @return Whether the event field is set.
     */
    boolean hasEvent();
    /**
     * <code>optional string event = 2;</code>
     * @return The event.
     */
    java.lang.String getEvent();
    /**
     * <code>optional string event = 2;</code>
     * @return The bytes for event.
     */
    com.google.protobuf.ByteString
        getEventBytes();

    /**
     * <code>optional .apollo.localization.Pose location = 3;</code>
     * @return Whether the location field is set.
     */
    boolean hasLocation();
    /**
     * <code>optional .apollo.localization.Pose location = 3;</code>
     * @return The location.
     */
    apollo.localization.PoseOuterClass.Pose getLocation();
    /**
     * <code>optional .apollo.localization.Pose location = 3;</code>
     */
    apollo.localization.PoseOuterClass.PoseOrBuilder getLocationOrBuilder();

    /**
     * <code>repeated .apollo.common.DriveEvent.Type type = 4;</code>
     * @return A list containing the type.
     */
    java.util.List<apollo.common.DriveEventOuterClass.DriveEvent.Type> getTypeList();
    /**
     * <code>repeated .apollo.common.DriveEvent.Type type = 4;</code>
     * @return The count of type.
     */
    int getTypeCount();
    /**
     * <code>repeated .apollo.common.DriveEvent.Type type = 4;</code>
     * @param index The index of the element to return.
     * @return The type at the given index.
     */
    apollo.common.DriveEventOuterClass.DriveEvent.Type getType(int index);

    /**
     * <code>optional bool is_reportable = 5;</code>
     * @return Whether the isReportable field is set.
     */
    boolean hasIsReportable();
    /**
     * <code>optional bool is_reportable = 5;</code>
     * @return The isReportable.
     */
    boolean getIsReportable();
  }
  /**
   * Protobuf type {@code apollo.common.DriveEvent}
   */
  public static final class DriveEvent extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:apollo.common.DriveEvent)
      DriveEventOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 1,
        /* suffix= */ "",
        DriveEvent.class.getName());
    }
    // Use DriveEvent.newBuilder() to construct.
    private DriveEvent(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private DriveEvent() {
      event_ = "";
      type_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return apollo.common.DriveEventOuterClass.internal_static_apollo_common_DriveEvent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return apollo.common.DriveEventOuterClass.internal_static_apollo_common_DriveEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              apollo.common.DriveEventOuterClass.DriveEvent.class, apollo.common.DriveEventOuterClass.DriveEvent.Builder.class);
    }

    /**
     * Protobuf enum {@code apollo.common.DriveEvent.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>CRITICAL = 0;</code>
       */
      CRITICAL(0),
      /**
       * <code>PROBLEM = 1;</code>
       */
      PROBLEM(1),
      /**
       * <code>DESIRED = 2;</code>
       */
      DESIRED(2),
      /**
       * <code>OUT_OF_SCOPE = 3;</code>
       */
      OUT_OF_SCOPE(3),
      ;

      static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
          com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
          /* major= */ 4,
          /* minor= */ 26,
          /* patch= */ 1,
          /* suffix= */ "",
          Type.class.getName());
      }
      /**
       * <code>CRITICAL = 0;</code>
       */
      public static final int CRITICAL_VALUE = 0;
      /**
       * <code>PROBLEM = 1;</code>
       */
      public static final int PROBLEM_VALUE = 1;
      /**
       * <code>DESIRED = 2;</code>
       */
      public static final int DESIRED_VALUE = 2;
      /**
       * <code>OUT_OF_SCOPE = 3;</code>
       */
      public static final int OUT_OF_SCOPE_VALUE = 3;


      public final int getNumber() {
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Type valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Type forNumber(int value) {
        switch (value) {
          case 0: return CRITICAL;
          case 1: return PROBLEM;
          case 2: return DESIRED;
          case 3: return OUT_OF_SCOPE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Type> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return apollo.common.DriveEventOuterClass.DriveEvent.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Type(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:apollo.common.DriveEvent.Type)
    }

    private int bitField0_;
    public static final int HEADER_FIELD_NUMBER = 1;
    private apollo.common.HeaderOuterClass.Header header_;
    /**
     * <code>optional .apollo.common.Header header = 1;</code>
     * @return Whether the header field is set.
     */
    @java.lang.Override
    public boolean hasHeader() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .apollo.common.Header header = 1;</code>
     * @return The header.
     */
    @java.lang.Override
    public apollo.common.HeaderOuterClass.Header getHeader() {
      return header_ == null ? apollo.common.HeaderOuterClass.Header.getDefaultInstance() : header_;
    }
    /**
     * <code>optional .apollo.common.Header header = 1;</code>
     */
    @java.lang.Override
    public apollo.common.HeaderOuterClass.HeaderOrBuilder getHeaderOrBuilder() {
      return header_ == null ? apollo.common.HeaderOuterClass.Header.getDefaultInstance() : header_;
    }

    public static final int EVENT_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object event_ = "";
    /**
     * <code>optional string event = 2;</code>
     * @return Whether the event field is set.
     */
    @java.lang.Override
    public boolean hasEvent() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string event = 2;</code>
     * @return The event.
     */
    @java.lang.Override
    public java.lang.String getEvent() {
      java.lang.Object ref = event_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          event_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string event = 2;</code>
     * @return The bytes for event.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEventBytes() {
      java.lang.Object ref = event_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        event_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LOCATION_FIELD_NUMBER = 3;
    private apollo.localization.PoseOuterClass.Pose location_;
    /**
     * <code>optional .apollo.localization.Pose location = 3;</code>
     * @return Whether the location field is set.
     */
    @java.lang.Override
    public boolean hasLocation() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional .apollo.localization.Pose location = 3;</code>
     * @return The location.
     */
    @java.lang.Override
    public apollo.localization.PoseOuterClass.Pose getLocation() {
      return location_ == null ? apollo.localization.PoseOuterClass.Pose.getDefaultInstance() : location_;
    }
    /**
     * <code>optional .apollo.localization.Pose location = 3;</code>
     */
    @java.lang.Override
    public apollo.localization.PoseOuterClass.PoseOrBuilder getLocationOrBuilder() {
      return location_ == null ? apollo.localization.PoseOuterClass.Pose.getDefaultInstance() : location_;
    }

    public static final int TYPE_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private java.util.List<java.lang.Integer> type_;
    private static final com.google.protobuf.Internal.ListAdapter.Converter<
        java.lang.Integer, apollo.common.DriveEventOuterClass.DriveEvent.Type> type_converter_ =
            new com.google.protobuf.Internal.ListAdapter.Converter<
                java.lang.Integer, apollo.common.DriveEventOuterClass.DriveEvent.Type>() {
              public apollo.common.DriveEventOuterClass.DriveEvent.Type convert(java.lang.Integer from) {
                apollo.common.DriveEventOuterClass.DriveEvent.Type result = apollo.common.DriveEventOuterClass.DriveEvent.Type.forNumber(from);
                return result == null ? apollo.common.DriveEventOuterClass.DriveEvent.Type.CRITICAL : result;
              }
            };
    /**
     * <code>repeated .apollo.common.DriveEvent.Type type = 4;</code>
     * @return A list containing the type.
     */
    @java.lang.Override
    public java.util.List<apollo.common.DriveEventOuterClass.DriveEvent.Type> getTypeList() {
      return new com.google.protobuf.Internal.ListAdapter<
          java.lang.Integer, apollo.common.DriveEventOuterClass.DriveEvent.Type>(type_, type_converter_);
    }
    /**
     * <code>repeated .apollo.common.DriveEvent.Type type = 4;</code>
     * @return The count of type.
     */
    @java.lang.Override
    public int getTypeCount() {
      return type_.size();
    }
    /**
     * <code>repeated .apollo.common.DriveEvent.Type type = 4;</code>
     * @param index The index of the element to return.
     * @return The type at the given index.
     */
    @java.lang.Override
    public apollo.common.DriveEventOuterClass.DriveEvent.Type getType(int index) {
      return type_converter_.convert(type_.get(index));
    }

    public static final int IS_REPORTABLE_FIELD_NUMBER = 5;
    private boolean isReportable_ = false;
    /**
     * <code>optional bool is_reportable = 5;</code>
     * @return Whether the isReportable field is set.
     */
    @java.lang.Override
    public boolean hasIsReportable() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional bool is_reportable = 5;</code>
     * @return The isReportable.
     */
    @java.lang.Override
    public boolean getIsReportable() {
      return isReportable_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getHeader());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, event_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeMessage(3, getLocation());
      }
      for (int i = 0; i < type_.size(); i++) {
        output.writeEnum(4, type_.get(i));
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeBool(5, isReportable_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getHeader());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, event_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getLocation());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < type_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeEnumSizeNoTag(type_.get(i));
        }
        size += dataSize;
        size += 1 * type_.size();
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, isReportable_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof apollo.common.DriveEventOuterClass.DriveEvent)) {
        return super.equals(obj);
      }
      apollo.common.DriveEventOuterClass.DriveEvent other = (apollo.common.DriveEventOuterClass.DriveEvent) obj;

      if (hasHeader() != other.hasHeader()) return false;
      if (hasHeader()) {
        if (!getHeader()
            .equals(other.getHeader())) return false;
      }
      if (hasEvent() != other.hasEvent()) return false;
      if (hasEvent()) {
        if (!getEvent()
            .equals(other.getEvent())) return false;
      }
      if (hasLocation() != other.hasLocation()) return false;
      if (hasLocation()) {
        if (!getLocation()
            .equals(other.getLocation())) return false;
      }
      if (!type_.equals(other.type_)) return false;
      if (hasIsReportable() != other.hasIsReportable()) return false;
      if (hasIsReportable()) {
        if (getIsReportable()
            != other.getIsReportable()) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasHeader()) {
        hash = (37 * hash) + HEADER_FIELD_NUMBER;
        hash = (53 * hash) + getHeader().hashCode();
      }
      if (hasEvent()) {
        hash = (37 * hash) + EVENT_FIELD_NUMBER;
        hash = (53 * hash) + getEvent().hashCode();
      }
      if (hasLocation()) {
        hash = (37 * hash) + LOCATION_FIELD_NUMBER;
        hash = (53 * hash) + getLocation().hashCode();
      }
      if (getTypeCount() > 0) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + type_.hashCode();
      }
      if (hasIsReportable()) {
        hash = (37 * hash) + IS_REPORTABLE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getIsReportable());
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static apollo.common.DriveEventOuterClass.DriveEvent parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static apollo.common.DriveEventOuterClass.DriveEvent parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static apollo.common.DriveEventOuterClass.DriveEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static apollo.common.DriveEventOuterClass.DriveEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static apollo.common.DriveEventOuterClass.DriveEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static apollo.common.DriveEventOuterClass.DriveEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static apollo.common.DriveEventOuterClass.DriveEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static apollo.common.DriveEventOuterClass.DriveEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static apollo.common.DriveEventOuterClass.DriveEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static apollo.common.DriveEventOuterClass.DriveEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static apollo.common.DriveEventOuterClass.DriveEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static apollo.common.DriveEventOuterClass.DriveEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(apollo.common.DriveEventOuterClass.DriveEvent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code apollo.common.DriveEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:apollo.common.DriveEvent)
        apollo.common.DriveEventOuterClass.DriveEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return apollo.common.DriveEventOuterClass.internal_static_apollo_common_DriveEvent_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return apollo.common.DriveEventOuterClass.internal_static_apollo_common_DriveEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                apollo.common.DriveEventOuterClass.DriveEvent.class, apollo.common.DriveEventOuterClass.DriveEvent.Builder.class);
      }

      // Construct using apollo.common.DriveEventOuterClass.DriveEvent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          getHeaderFieldBuilder();
          getLocationFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        header_ = null;
        if (headerBuilder_ != null) {
          headerBuilder_.dispose();
          headerBuilder_ = null;
        }
        event_ = "";
        location_ = null;
        if (locationBuilder_ != null) {
          locationBuilder_.dispose();
          locationBuilder_ = null;
        }
        type_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        isReportable_ = false;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return apollo.common.DriveEventOuterClass.internal_static_apollo_common_DriveEvent_descriptor;
      }

      @java.lang.Override
      public apollo.common.DriveEventOuterClass.DriveEvent getDefaultInstanceForType() {
        return apollo.common.DriveEventOuterClass.DriveEvent.getDefaultInstance();
      }

      @java.lang.Override
      public apollo.common.DriveEventOuterClass.DriveEvent build() {
        apollo.common.DriveEventOuterClass.DriveEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public apollo.common.DriveEventOuterClass.DriveEvent buildPartial() {
        apollo.common.DriveEventOuterClass.DriveEvent result = new apollo.common.DriveEventOuterClass.DriveEvent(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(apollo.common.DriveEventOuterClass.DriveEvent result) {
        if (((bitField0_ & 0x00000008) != 0)) {
          type_ = java.util.Collections.unmodifiableList(type_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.type_ = type_;
      }

      private void buildPartial0(apollo.common.DriveEventOuterClass.DriveEvent result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.header_ = headerBuilder_ == null
              ? header_
              : headerBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.event_ = event_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.location_ = locationBuilder_ == null
              ? location_
              : locationBuilder_.build();
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.isReportable_ = isReportable_;
          to_bitField0_ |= 0x00000008;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof apollo.common.DriveEventOuterClass.DriveEvent) {
          return mergeFrom((apollo.common.DriveEventOuterClass.DriveEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(apollo.common.DriveEventOuterClass.DriveEvent other) {
        if (other == apollo.common.DriveEventOuterClass.DriveEvent.getDefaultInstance()) return this;
        if (other.hasHeader()) {
          mergeHeader(other.getHeader());
        }
        if (other.hasEvent()) {
          event_ = other.event_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.hasLocation()) {
          mergeLocation(other.getLocation());
        }
        if (!other.type_.isEmpty()) {
          if (type_.isEmpty()) {
            type_ = other.type_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureTypeIsMutable();
            type_.addAll(other.type_);
          }
          onChanged();
        }
        if (other.hasIsReportable()) {
          setIsReportable(other.getIsReportable());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getHeaderFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                event_ = input.readBytes();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                input.readMessage(
                    getLocationFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 32: {
                int tmpRaw = input.readEnum();
                apollo.common.DriveEventOuterClass.DriveEvent.Type tmpValue =
                    apollo.common.DriveEventOuterClass.DriveEvent.Type.forNumber(tmpRaw);
                if (tmpValue == null) {
                  mergeUnknownVarintField(4, tmpRaw);
                } else {
                  ensureTypeIsMutable();
                  type_.add(tmpRaw);
                }
                break;
              } // case 32
              case 34: {
                int length = input.readRawVarint32();
                int oldLimit = input.pushLimit(length);
                while(input.getBytesUntilLimit() > 0) {
                  int tmpRaw = input.readEnum();
                  apollo.common.DriveEventOuterClass.DriveEvent.Type tmpValue =
                      apollo.common.DriveEventOuterClass.DriveEvent.Type.forNumber(tmpRaw);
                  if (tmpValue == null) {
                    mergeUnknownVarintField(4, tmpRaw);
                  } else {
                    ensureTypeIsMutable();
                    type_.add(tmpRaw);
                  }
                }
                input.popLimit(oldLimit);
                break;
              } // case 34
              case 40: {
                isReportable_ = input.readBool();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private apollo.common.HeaderOuterClass.Header header_;
      private com.google.protobuf.SingleFieldBuilder<
          apollo.common.HeaderOuterClass.Header, apollo.common.HeaderOuterClass.Header.Builder, apollo.common.HeaderOuterClass.HeaderOrBuilder> headerBuilder_;
      /**
       * <code>optional .apollo.common.Header header = 1;</code>
       * @return Whether the header field is set.
       */
      public boolean hasHeader() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional .apollo.common.Header header = 1;</code>
       * @return The header.
       */
      public apollo.common.HeaderOuterClass.Header getHeader() {
        if (headerBuilder_ == null) {
          return header_ == null ? apollo.common.HeaderOuterClass.Header.getDefaultInstance() : header_;
        } else {
          return headerBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .apollo.common.Header header = 1;</code>
       */
      public Builder setHeader(apollo.common.HeaderOuterClass.Header value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          header_ = value;
        } else {
          headerBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional .apollo.common.Header header = 1;</code>
       */
      public Builder setHeader(
          apollo.common.HeaderOuterClass.Header.Builder builderForValue) {
        if (headerBuilder_ == null) {
          header_ = builderForValue.build();
        } else {
          headerBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional .apollo.common.Header header = 1;</code>
       */
      public Builder mergeHeader(apollo.common.HeaderOuterClass.Header value) {
        if (headerBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            header_ != null &&
            header_ != apollo.common.HeaderOuterClass.Header.getDefaultInstance()) {
            getHeaderBuilder().mergeFrom(value);
          } else {
            header_ = value;
          }
        } else {
          headerBuilder_.mergeFrom(value);
        }
        if (header_ != null) {
          bitField0_ |= 0x00000001;
          onChanged();
        }
        return this;
      }
      /**
       * <code>optional .apollo.common.Header header = 1;</code>
       */
      public Builder clearHeader() {
        bitField0_ = (bitField0_ & ~0x00000001);
        header_ = null;
        if (headerBuilder_ != null) {
          headerBuilder_.dispose();
          headerBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>optional .apollo.common.Header header = 1;</code>
       */
      public apollo.common.HeaderOuterClass.Header.Builder getHeaderBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getHeaderFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .apollo.common.Header header = 1;</code>
       */
      public apollo.common.HeaderOuterClass.HeaderOrBuilder getHeaderOrBuilder() {
        if (headerBuilder_ != null) {
          return headerBuilder_.getMessageOrBuilder();
        } else {
          return header_ == null ?
              apollo.common.HeaderOuterClass.Header.getDefaultInstance() : header_;
        }
      }
      /**
       * <code>optional .apollo.common.Header header = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          apollo.common.HeaderOuterClass.Header, apollo.common.HeaderOuterClass.Header.Builder, apollo.common.HeaderOuterClass.HeaderOrBuilder> 
          getHeaderFieldBuilder() {
        if (headerBuilder_ == null) {
          headerBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              apollo.common.HeaderOuterClass.Header, apollo.common.HeaderOuterClass.Header.Builder, apollo.common.HeaderOuterClass.HeaderOrBuilder>(
                  getHeader(),
                  getParentForChildren(),
                  isClean());
          header_ = null;
        }
        return headerBuilder_;
      }

      private java.lang.Object event_ = "";
      /**
       * <code>optional string event = 2;</code>
       * @return Whether the event field is set.
       */
      public boolean hasEvent() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string event = 2;</code>
       * @return The event.
       */
      public java.lang.String getEvent() {
        java.lang.Object ref = event_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            event_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string event = 2;</code>
       * @return The bytes for event.
       */
      public com.google.protobuf.ByteString
          getEventBytes() {
        java.lang.Object ref = event_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          event_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string event = 2;</code>
       * @param value The event to set.
       * @return This builder for chaining.
       */
      public Builder setEvent(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        event_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional string event = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearEvent() {
        event_ = getDefaultInstance().getEvent();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>optional string event = 2;</code>
       * @param value The bytes for event to set.
       * @return This builder for chaining.
       */
      public Builder setEventBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        event_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private apollo.localization.PoseOuterClass.Pose location_;
      private com.google.protobuf.SingleFieldBuilder<
          apollo.localization.PoseOuterClass.Pose, apollo.localization.PoseOuterClass.Pose.Builder, apollo.localization.PoseOuterClass.PoseOrBuilder> locationBuilder_;
      /**
       * <code>optional .apollo.localization.Pose location = 3;</code>
       * @return Whether the location field is set.
       */
      public boolean hasLocation() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional .apollo.localization.Pose location = 3;</code>
       * @return The location.
       */
      public apollo.localization.PoseOuterClass.Pose getLocation() {
        if (locationBuilder_ == null) {
          return location_ == null ? apollo.localization.PoseOuterClass.Pose.getDefaultInstance() : location_;
        } else {
          return locationBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .apollo.localization.Pose location = 3;</code>
       */
      public Builder setLocation(apollo.localization.PoseOuterClass.Pose value) {
        if (locationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          location_ = value;
        } else {
          locationBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>optional .apollo.localization.Pose location = 3;</code>
       */
      public Builder setLocation(
          apollo.localization.PoseOuterClass.Pose.Builder builderForValue) {
        if (locationBuilder_ == null) {
          location_ = builderForValue.build();
        } else {
          locationBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>optional .apollo.localization.Pose location = 3;</code>
       */
      public Builder mergeLocation(apollo.localization.PoseOuterClass.Pose value) {
        if (locationBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0) &&
            location_ != null &&
            location_ != apollo.localization.PoseOuterClass.Pose.getDefaultInstance()) {
            getLocationBuilder().mergeFrom(value);
          } else {
            location_ = value;
          }
        } else {
          locationBuilder_.mergeFrom(value);
        }
        if (location_ != null) {
          bitField0_ |= 0x00000004;
          onChanged();
        }
        return this;
      }
      /**
       * <code>optional .apollo.localization.Pose location = 3;</code>
       */
      public Builder clearLocation() {
        bitField0_ = (bitField0_ & ~0x00000004);
        location_ = null;
        if (locationBuilder_ != null) {
          locationBuilder_.dispose();
          locationBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>optional .apollo.localization.Pose location = 3;</code>
       */
      public apollo.localization.PoseOuterClass.Pose.Builder getLocationBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getLocationFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .apollo.localization.Pose location = 3;</code>
       */
      public apollo.localization.PoseOuterClass.PoseOrBuilder getLocationOrBuilder() {
        if (locationBuilder_ != null) {
          return locationBuilder_.getMessageOrBuilder();
        } else {
          return location_ == null ?
              apollo.localization.PoseOuterClass.Pose.getDefaultInstance() : location_;
        }
      }
      /**
       * <code>optional .apollo.localization.Pose location = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          apollo.localization.PoseOuterClass.Pose, apollo.localization.PoseOuterClass.Pose.Builder, apollo.localization.PoseOuterClass.PoseOrBuilder> 
          getLocationFieldBuilder() {
        if (locationBuilder_ == null) {
          locationBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              apollo.localization.PoseOuterClass.Pose, apollo.localization.PoseOuterClass.Pose.Builder, apollo.localization.PoseOuterClass.PoseOrBuilder>(
                  getLocation(),
                  getParentForChildren(),
                  isClean());
          location_ = null;
        }
        return locationBuilder_;
      }

      private java.util.List<java.lang.Integer> type_ =
        java.util.Collections.emptyList();
      private void ensureTypeIsMutable() {
        if (!((bitField0_ & 0x00000008) != 0)) {
          type_ = new java.util.ArrayList<java.lang.Integer>(type_);
          bitField0_ |= 0x00000008;
        }
      }
      /**
       * <code>repeated .apollo.common.DriveEvent.Type type = 4;</code>
       * @return A list containing the type.
       */
      public java.util.List<apollo.common.DriveEventOuterClass.DriveEvent.Type> getTypeList() {
        return new com.google.protobuf.Internal.ListAdapter<
            java.lang.Integer, apollo.common.DriveEventOuterClass.DriveEvent.Type>(type_, type_converter_);
      }
      /**
       * <code>repeated .apollo.common.DriveEvent.Type type = 4;</code>
       * @return The count of type.
       */
      public int getTypeCount() {
        return type_.size();
      }
      /**
       * <code>repeated .apollo.common.DriveEvent.Type type = 4;</code>
       * @param index The index of the element to return.
       * @return The type at the given index.
       */
      public apollo.common.DriveEventOuterClass.DriveEvent.Type getType(int index) {
        return type_converter_.convert(type_.get(index));
      }
      /**
       * <code>repeated .apollo.common.DriveEvent.Type type = 4;</code>
       * @param index The index to set the value at.
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(
          int index, apollo.common.DriveEventOuterClass.DriveEvent.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTypeIsMutable();
        type_.set(index, value.getNumber());
        onChanged();
        return this;
      }
      /**
       * <code>repeated .apollo.common.DriveEvent.Type type = 4;</code>
       * @param value The type to add.
       * @return This builder for chaining.
       */
      public Builder addType(apollo.common.DriveEventOuterClass.DriveEvent.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTypeIsMutable();
        type_.add(value.getNumber());
        onChanged();
        return this;
      }
      /**
       * <code>repeated .apollo.common.DriveEvent.Type type = 4;</code>
       * @param values The type to add.
       * @return This builder for chaining.
       */
      public Builder addAllType(
          java.lang.Iterable<? extends apollo.common.DriveEventOuterClass.DriveEvent.Type> values) {
        ensureTypeIsMutable();
        for (apollo.common.DriveEventOuterClass.DriveEvent.Type value : values) {
          type_.add(value.getNumber());
        }
        onChanged();
        return this;
      }
      /**
       * <code>repeated .apollo.common.DriveEvent.Type type = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        type_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }

      private boolean isReportable_ ;
      /**
       * <code>optional bool is_reportable = 5;</code>
       * @return Whether the isReportable field is set.
       */
      @java.lang.Override
      public boolean hasIsReportable() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional bool is_reportable = 5;</code>
       * @return The isReportable.
       */
      @java.lang.Override
      public boolean getIsReportable() {
        return isReportable_;
      }
      /**
       * <code>optional bool is_reportable = 5;</code>
       * @param value The isReportable to set.
       * @return This builder for chaining.
       */
      public Builder setIsReportable(boolean value) {

        isReportable_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool is_reportable = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsReportable() {
        bitField0_ = (bitField0_ & ~0x00000010);
        isReportable_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:apollo.common.DriveEvent)
    }

    // @@protoc_insertion_point(class_scope:apollo.common.DriveEvent)
    private static final apollo.common.DriveEventOuterClass.DriveEvent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new apollo.common.DriveEventOuterClass.DriveEvent();
    }

    public static apollo.common.DriveEventOuterClass.DriveEvent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DriveEvent>
        PARSER = new com.google.protobuf.AbstractParser<DriveEvent>() {
      @java.lang.Override
      public DriveEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<DriveEvent> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DriveEvent> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public apollo.common.DriveEventOuterClass.DriveEvent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apollo_common_DriveEvent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_apollo_common_DriveEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n&modules/common/proto/drive_event.proto" +
      "\022\rapollo.common\032!modules/common/proto/he" +
      "ader.proto\032%modules/localization/proto/p" +
      "ose.proto\"\366\001\n\nDriveEvent\022%\n\006header\030\001 \001(\013" +
      "2\025.apollo.common.Header\022\r\n\005event\030\002 \001(\t\022+" +
      "\n\010location\030\003 \001(\0132\031.apollo.localization.P" +
      "ose\022,\n\004type\030\004 \003(\0162\036.apollo.common.DriveE" +
      "vent.Type\022\025\n\ris_reportable\030\005 \001(\010\"@\n\004Type" +
      "\022\014\n\010CRITICAL\020\000\022\013\n\007PROBLEM\020\001\022\013\n\007DESIRED\020\002" +
      "\022\020\n\014OUT_OF_SCOPE\020\003"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          apollo.common.HeaderOuterClass.getDescriptor(),
          apollo.localization.PoseOuterClass.getDescriptor(),
        });
    internal_static_apollo_common_DriveEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_apollo_common_DriveEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_apollo_common_DriveEvent_descriptor,
        new java.lang.String[] { "Header", "Event", "Location", "Type", "IsReportable", });
    descriptor.resolveAllFeaturesImmutable();
    apollo.common.HeaderOuterClass.getDescriptor();
    apollo.localization.PoseOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
