// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: modules/drivers/proto/pointcloud.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package apollo.drivers;

