// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: modules/localization/proto/localization.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package apollo.localization;

