// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: modules/localization/proto/localization_status.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package apollo.localization;

@kotlin.jvm.JvmName("-initializemsfSensorMsgStatus")
public inline fun msfSensorMsgStatus(block: apollo.localization.MsfSensorMsgStatusKt.Dsl.() -> kotlin.Unit): apollo.localization.LocalizationStatus.MsfSensorMsgStatus =
  apollo.localization.MsfSensorMsgStatusKt.Dsl._create(apollo.localization.LocalizationStatus.MsfSensorMsgStatus.newBuilder()).apply { block() }._build()
/**
 * ```
 * The status of sensor msg
 * ```
 *
 * Protobuf type `apollo.localization.MsfSensorMsgStatus`
 */
public object MsfSensorMsgStatusKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: apollo.localization.LocalizationStatus.MsfSensorMsgStatus.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: apollo.localization.LocalizationStatus.MsfSensorMsgStatus.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): apollo.localization.LocalizationStatus.MsfSensorMsgStatus = _builder.build()

    /**
     * `optional .apollo.localization.ImuMsgDelayStatus imu_delay_status = 1;`
     */
    public var imuDelayStatus: apollo.localization.LocalizationStatus.ImuMsgDelayStatus
      @JvmName("getImuDelayStatus")
      get() = _builder.getImuDelayStatus()
      @JvmName("setImuDelayStatus")
      set(value) {
        _builder.setImuDelayStatus(value)
      }
    /**
     * `optional .apollo.localization.ImuMsgDelayStatus imu_delay_status = 1;`
     */
    public fun clearImuDelayStatus() {
      _builder.clearImuDelayStatus()
    }
    /**
     * `optional .apollo.localization.ImuMsgDelayStatus imu_delay_status = 1;`
     * @return Whether the imuDelayStatus field is set.
     */
    public fun hasImuDelayStatus(): kotlin.Boolean {
      return _builder.hasImuDelayStatus()
    }

    /**
     * `optional .apollo.localization.ImuMsgMissingStatus imu_missing_status = 2;`
     */
    public var imuMissingStatus: apollo.localization.LocalizationStatus.ImuMsgMissingStatus
      @JvmName("getImuMissingStatus")
      get() = _builder.getImuMissingStatus()
      @JvmName("setImuMissingStatus")
      set(value) {
        _builder.setImuMissingStatus(value)
      }
    /**
     * `optional .apollo.localization.ImuMsgMissingStatus imu_missing_status = 2;`
     */
    public fun clearImuMissingStatus() {
      _builder.clearImuMissingStatus()
    }
    /**
     * `optional .apollo.localization.ImuMsgMissingStatus imu_missing_status = 2;`
     * @return Whether the imuMissingStatus field is set.
     */
    public fun hasImuMissingStatus(): kotlin.Boolean {
      return _builder.hasImuMissingStatus()
    }

    /**
     * `optional .apollo.localization.ImuMsgDataStatus imu_data_status = 3;`
     */
    public var imuDataStatus: apollo.localization.LocalizationStatus.ImuMsgDataStatus
      @JvmName("getImuDataStatus")
      get() = _builder.getImuDataStatus()
      @JvmName("setImuDataStatus")
      set(value) {
        _builder.setImuDataStatus(value)
      }
    /**
     * `optional .apollo.localization.ImuMsgDataStatus imu_data_status = 3;`
     */
    public fun clearImuDataStatus() {
      _builder.clearImuDataStatus()
    }
    /**
     * `optional .apollo.localization.ImuMsgDataStatus imu_data_status = 3;`
     * @return Whether the imuDataStatus field is set.
     */
    public fun hasImuDataStatus(): kotlin.Boolean {
      return _builder.hasImuDataStatus()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun apollo.localization.LocalizationStatus.MsfSensorMsgStatus.copy(block: `apollo.localization`.MsfSensorMsgStatusKt.Dsl.() -> kotlin.Unit): apollo.localization.LocalizationStatus.MsfSensorMsgStatus =
  `apollo.localization`.MsfSensorMsgStatusKt.Dsl._create(this.toBuilder()).apply { block() }._build()

