// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: modules/map/proto/map_geometry.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package apollo.hdmap;

