// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: modules/common/proto/geometry.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package apollo.common;

@kotlin.jvm.JvmName("-initializepoint3D")
public inline fun point3D(block: apollo.common.Point3DKt.Dsl.() -> kotlin.Unit): apollo.common.Geometry.Point3D =
  apollo.common.Point3DKt.Dsl._create(apollo.common.Geometry.Point3D.newBuilder()).apply { block() }._build()
/**
 * ```
 * A general 3D point. Its meaning and units depend on context, and must be
 * explained in comments.
 * ```
 *
 * Protobuf type `apollo.common.Point3D`
 */
public object Point3DKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: apollo.common.Geometry.Point3D.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: apollo.common.Geometry.Point3D.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): apollo.common.Geometry.Point3D = _builder.build()

    /**
     * `optional double x = 1 [default = nan];`
     */
    public var x: kotlin.Double
      @JvmName("getX")
      get() = _builder.getX()
      @JvmName("setX")
      set(value) {
        _builder.setX(value)
      }
    /**
     * `optional double x = 1 [default = nan];`
     */
    public fun clearX() {
      _builder.clearX()
    }
    /**
     * `optional double x = 1 [default = nan];`
     * @return Whether the x field is set.
     */
    public fun hasX(): kotlin.Boolean {
      return _builder.hasX()
    }

    /**
     * `optional double y = 2 [default = nan];`
     */
    public var y: kotlin.Double
      @JvmName("getY")
      get() = _builder.getY()
      @JvmName("setY")
      set(value) {
        _builder.setY(value)
      }
    /**
     * `optional double y = 2 [default = nan];`
     */
    public fun clearY() {
      _builder.clearY()
    }
    /**
     * `optional double y = 2 [default = nan];`
     * @return Whether the y field is set.
     */
    public fun hasY(): kotlin.Boolean {
      return _builder.hasY()
    }

    /**
     * `optional double z = 3 [default = nan];`
     */
    public var z: kotlin.Double
      @JvmName("getZ")
      get() = _builder.getZ()
      @JvmName("setZ")
      set(value) {
        _builder.setZ(value)
      }
    /**
     * `optional double z = 3 [default = nan];`
     */
    public fun clearZ() {
      _builder.clearZ()
    }
    /**
     * `optional double z = 3 [default = nan];`
     * @return Whether the z field is set.
     */
    public fun hasZ(): kotlin.Boolean {
      return _builder.hasZ()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun apollo.common.Geometry.Point3D.copy(block: `apollo.common`.Point3DKt.Dsl.() -> kotlin.Unit): apollo.common.Geometry.Point3D =
  `apollo.common`.Point3DKt.Dsl._create(this.toBuilder()).apply { block() }._build()

