// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: modules/perception/proto/perception_obstacle.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package apollo.perception;

@kotlin.jvm.JvmName("-initializelaneMarkers")
public inline fun laneMarkers(block: apollo.perception.LaneMarkersKt.Dsl.() -> kotlin.Unit): apollo.perception.PerceptionObstacleOuterClass.LaneMarkers =
  apollo.perception.LaneMarkersKt.Dsl._create(apollo.perception.PerceptionObstacleOuterClass.LaneMarkers.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `apollo.perception.LaneMarkers`
 */
public object LaneMarkersKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: apollo.perception.PerceptionObstacleOuterClass.LaneMarkers.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: apollo.perception.PerceptionObstacleOuterClass.LaneMarkers.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): apollo.perception.PerceptionObstacleOuterClass.LaneMarkers = _builder.build()

    /**
     * `optional .apollo.perception.LaneMarker left_lane_marker = 1;`
     */
    public var leftLaneMarker: apollo.perception.PerceptionObstacleOuterClass.LaneMarker
      @JvmName("getLeftLaneMarker")
      get() = _builder.getLeftLaneMarker()
      @JvmName("setLeftLaneMarker")
      set(value) {
        _builder.setLeftLaneMarker(value)
      }
    /**
     * `optional .apollo.perception.LaneMarker left_lane_marker = 1;`
     */
    public fun clearLeftLaneMarker() {
      _builder.clearLeftLaneMarker()
    }
    /**
     * `optional .apollo.perception.LaneMarker left_lane_marker = 1;`
     * @return Whether the leftLaneMarker field is set.
     */
    public fun hasLeftLaneMarker(): kotlin.Boolean {
      return _builder.hasLeftLaneMarker()
    }
    public val LaneMarkersKt.Dsl.leftLaneMarkerOrNull: apollo.perception.PerceptionObstacleOuterClass.LaneMarker?
      get() = _builder.leftLaneMarkerOrNull

    /**
     * `optional .apollo.perception.LaneMarker right_lane_marker = 2;`
     */
    public var rightLaneMarker: apollo.perception.PerceptionObstacleOuterClass.LaneMarker
      @JvmName("getRightLaneMarker")
      get() = _builder.getRightLaneMarker()
      @JvmName("setRightLaneMarker")
      set(value) {
        _builder.setRightLaneMarker(value)
      }
    /**
     * `optional .apollo.perception.LaneMarker right_lane_marker = 2;`
     */
    public fun clearRightLaneMarker() {
      _builder.clearRightLaneMarker()
    }
    /**
     * `optional .apollo.perception.LaneMarker right_lane_marker = 2;`
     * @return Whether the rightLaneMarker field is set.
     */
    public fun hasRightLaneMarker(): kotlin.Boolean {
      return _builder.hasRightLaneMarker()
    }
    public val LaneMarkersKt.Dsl.rightLaneMarkerOrNull: apollo.perception.PerceptionObstacleOuterClass.LaneMarker?
      get() = _builder.rightLaneMarkerOrNull

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class NextLeftLaneMarkerProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .apollo.perception.LaneMarker next_left_lane_marker = 3;`
     */
     public val nextLeftLaneMarker: com.google.protobuf.kotlin.DslList<apollo.perception.PerceptionObstacleOuterClass.LaneMarker, NextLeftLaneMarkerProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getNextLeftLaneMarkerList()
      )
    /**
     * `repeated .apollo.perception.LaneMarker next_left_lane_marker = 3;`
     * @param value The nextLeftLaneMarker to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addNextLeftLaneMarker")
    public fun com.google.protobuf.kotlin.DslList<apollo.perception.PerceptionObstacleOuterClass.LaneMarker, NextLeftLaneMarkerProxy>.add(value: apollo.perception.PerceptionObstacleOuterClass.LaneMarker) {
      _builder.addNextLeftLaneMarker(value)
    }
    /**
     * `repeated .apollo.perception.LaneMarker next_left_lane_marker = 3;`
     * @param value The nextLeftLaneMarker to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignNextLeftLaneMarker")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<apollo.perception.PerceptionObstacleOuterClass.LaneMarker, NextLeftLaneMarkerProxy>.plusAssign(value: apollo.perception.PerceptionObstacleOuterClass.LaneMarker) {
      add(value)
    }
    /**
     * `repeated .apollo.perception.LaneMarker next_left_lane_marker = 3;`
     * @param values The nextLeftLaneMarker to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllNextLeftLaneMarker")
    public fun com.google.protobuf.kotlin.DslList<apollo.perception.PerceptionObstacleOuterClass.LaneMarker, NextLeftLaneMarkerProxy>.addAll(values: kotlin.collections.Iterable<apollo.perception.PerceptionObstacleOuterClass.LaneMarker>) {
      _builder.addAllNextLeftLaneMarker(values)
    }
    /**
     * `repeated .apollo.perception.LaneMarker next_left_lane_marker = 3;`
     * @param values The nextLeftLaneMarker to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllNextLeftLaneMarker")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<apollo.perception.PerceptionObstacleOuterClass.LaneMarker, NextLeftLaneMarkerProxy>.plusAssign(values: kotlin.collections.Iterable<apollo.perception.PerceptionObstacleOuterClass.LaneMarker>) {
      addAll(values)
    }
    /**
     * `repeated .apollo.perception.LaneMarker next_left_lane_marker = 3;`
     * @param index The index to set the value at.
     * @param value The nextLeftLaneMarker to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setNextLeftLaneMarker")
    public operator fun com.google.protobuf.kotlin.DslList<apollo.perception.PerceptionObstacleOuterClass.LaneMarker, NextLeftLaneMarkerProxy>.set(index: kotlin.Int, value: apollo.perception.PerceptionObstacleOuterClass.LaneMarker) {
      _builder.setNextLeftLaneMarker(index, value)
    }
    /**
     * `repeated .apollo.perception.LaneMarker next_left_lane_marker = 3;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearNextLeftLaneMarker")
    public fun com.google.protobuf.kotlin.DslList<apollo.perception.PerceptionObstacleOuterClass.LaneMarker, NextLeftLaneMarkerProxy>.clear() {
      _builder.clearNextLeftLaneMarker()
    }


    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class NextRightLaneMarkerProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .apollo.perception.LaneMarker next_right_lane_marker = 4;`
     */
     public val nextRightLaneMarker: com.google.protobuf.kotlin.DslList<apollo.perception.PerceptionObstacleOuterClass.LaneMarker, NextRightLaneMarkerProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getNextRightLaneMarkerList()
      )
    /**
     * `repeated .apollo.perception.LaneMarker next_right_lane_marker = 4;`
     * @param value The nextRightLaneMarker to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addNextRightLaneMarker")
    public fun com.google.protobuf.kotlin.DslList<apollo.perception.PerceptionObstacleOuterClass.LaneMarker, NextRightLaneMarkerProxy>.add(value: apollo.perception.PerceptionObstacleOuterClass.LaneMarker) {
      _builder.addNextRightLaneMarker(value)
    }
    /**
     * `repeated .apollo.perception.LaneMarker next_right_lane_marker = 4;`
     * @param value The nextRightLaneMarker to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignNextRightLaneMarker")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<apollo.perception.PerceptionObstacleOuterClass.LaneMarker, NextRightLaneMarkerProxy>.plusAssign(value: apollo.perception.PerceptionObstacleOuterClass.LaneMarker) {
      add(value)
    }
    /**
     * `repeated .apollo.perception.LaneMarker next_right_lane_marker = 4;`
     * @param values The nextRightLaneMarker to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllNextRightLaneMarker")
    public fun com.google.protobuf.kotlin.DslList<apollo.perception.PerceptionObstacleOuterClass.LaneMarker, NextRightLaneMarkerProxy>.addAll(values: kotlin.collections.Iterable<apollo.perception.PerceptionObstacleOuterClass.LaneMarker>) {
      _builder.addAllNextRightLaneMarker(values)
    }
    /**
     * `repeated .apollo.perception.LaneMarker next_right_lane_marker = 4;`
     * @param values The nextRightLaneMarker to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllNextRightLaneMarker")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<apollo.perception.PerceptionObstacleOuterClass.LaneMarker, NextRightLaneMarkerProxy>.plusAssign(values: kotlin.collections.Iterable<apollo.perception.PerceptionObstacleOuterClass.LaneMarker>) {
      addAll(values)
    }
    /**
     * `repeated .apollo.perception.LaneMarker next_right_lane_marker = 4;`
     * @param index The index to set the value at.
     * @param value The nextRightLaneMarker to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setNextRightLaneMarker")
    public operator fun com.google.protobuf.kotlin.DslList<apollo.perception.PerceptionObstacleOuterClass.LaneMarker, NextRightLaneMarkerProxy>.set(index: kotlin.Int, value: apollo.perception.PerceptionObstacleOuterClass.LaneMarker) {
      _builder.setNextRightLaneMarker(index, value)
    }
    /**
     * `repeated .apollo.perception.LaneMarker next_right_lane_marker = 4;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearNextRightLaneMarker")
    public fun com.google.protobuf.kotlin.DslList<apollo.perception.PerceptionObstacleOuterClass.LaneMarker, NextRightLaneMarkerProxy>.clear() {
      _builder.clearNextRightLaneMarker()
    }

  }
}
@kotlin.jvm.JvmSynthetic
public inline fun apollo.perception.PerceptionObstacleOuterClass.LaneMarkers.copy(block: `apollo.perception`.LaneMarkersKt.Dsl.() -> kotlin.Unit): apollo.perception.PerceptionObstacleOuterClass.LaneMarkers =
  `apollo.perception`.LaneMarkersKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val apollo.perception.PerceptionObstacleOuterClass.LaneMarkersOrBuilder.leftLaneMarkerOrNull: apollo.perception.PerceptionObstacleOuterClass.LaneMarker?
  get() = if (hasLeftLaneMarker()) getLeftLaneMarker() else null

public val apollo.perception.PerceptionObstacleOuterClass.LaneMarkersOrBuilder.rightLaneMarkerOrNull: apollo.perception.PerceptionObstacleOuterClass.LaneMarker?
  get() = if (hasRightLaneMarker()) getRightLaneMarker() else null

