// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: modules/essys/lidar_cali.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package essys_middle;

