// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/dreamview/proto/point_cloud.proto
// Protobuf Java Version: 4.26.1

package apollo.dreamview;

public final class PointCloudOuterClass {
  private PointCloudOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      PointCloudOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PointCloudOrBuilder extends
      // @@protoc_insertion_point(interface_extends:apollo.dreamview.PointCloud)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated float num = 1 [packed = true];</code>
     * @return A list containing the num.
     */
    java.util.List<java.lang.Float> getNumList();
    /**
     * <code>repeated float num = 1 [packed = true];</code>
     * @return The count of num.
     */
    int getNumCount();
    /**
     * <code>repeated float num = 1 [packed = true];</code>
     * @param index The index of the element to return.
     * @return The num at the given index.
     */
    float getNum(int index);
  }
  /**
   * Protobuf type {@code apollo.dreamview.PointCloud}
   */
  public static final class PointCloud extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:apollo.dreamview.PointCloud)
      PointCloudOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 1,
        /* suffix= */ "",
        PointCloud.class.getName());
    }
    // Use PointCloud.newBuilder() to construct.
    private PointCloud(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private PointCloud() {
      num_ = emptyFloatList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return apollo.dreamview.PointCloudOuterClass.internal_static_apollo_dreamview_PointCloud_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return apollo.dreamview.PointCloudOuterClass.internal_static_apollo_dreamview_PointCloud_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              apollo.dreamview.PointCloudOuterClass.PointCloud.class, apollo.dreamview.PointCloudOuterClass.PointCloud.Builder.class);
    }

    public static final int NUM_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private com.google.protobuf.Internal.FloatList num_ =
        emptyFloatList();
    /**
     * <code>repeated float num = 1 [packed = true];</code>
     * @return A list containing the num.
     */
    @java.lang.Override
    public java.util.List<java.lang.Float>
        getNumList() {
      return num_;
    }
    /**
     * <code>repeated float num = 1 [packed = true];</code>
     * @return The count of num.
     */
    public int getNumCount() {
      return num_.size();
    }
    /**
     * <code>repeated float num = 1 [packed = true];</code>
     * @param index The index of the element to return.
     * @return The num at the given index.
     */
    public float getNum(int index) {
      return num_.getFloat(index);
    }
    private int numMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getNumList().size() > 0) {
        output.writeUInt32NoTag(10);
        output.writeUInt32NoTag(numMemoizedSerializedSize);
      }
      for (int i = 0; i < num_.size(); i++) {
        output.writeFloatNoTag(num_.getFloat(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        dataSize = 4 * getNumList().size();
        size += dataSize;
        if (!getNumList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        numMemoizedSerializedSize = dataSize;
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof apollo.dreamview.PointCloudOuterClass.PointCloud)) {
        return super.equals(obj);
      }
      apollo.dreamview.PointCloudOuterClass.PointCloud other = (apollo.dreamview.PointCloudOuterClass.PointCloud) obj;

      if (!getNumList()
          .equals(other.getNumList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getNumCount() > 0) {
        hash = (37 * hash) + NUM_FIELD_NUMBER;
        hash = (53 * hash) + getNumList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static apollo.dreamview.PointCloudOuterClass.PointCloud parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static apollo.dreamview.PointCloudOuterClass.PointCloud parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static apollo.dreamview.PointCloudOuterClass.PointCloud parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static apollo.dreamview.PointCloudOuterClass.PointCloud parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static apollo.dreamview.PointCloudOuterClass.PointCloud parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static apollo.dreamview.PointCloudOuterClass.PointCloud parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static apollo.dreamview.PointCloudOuterClass.PointCloud parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static apollo.dreamview.PointCloudOuterClass.PointCloud parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static apollo.dreamview.PointCloudOuterClass.PointCloud parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static apollo.dreamview.PointCloudOuterClass.PointCloud parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static apollo.dreamview.PointCloudOuterClass.PointCloud parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static apollo.dreamview.PointCloudOuterClass.PointCloud parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(apollo.dreamview.PointCloudOuterClass.PointCloud prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code apollo.dreamview.PointCloud}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:apollo.dreamview.PointCloud)
        apollo.dreamview.PointCloudOuterClass.PointCloudOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return apollo.dreamview.PointCloudOuterClass.internal_static_apollo_dreamview_PointCloud_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return apollo.dreamview.PointCloudOuterClass.internal_static_apollo_dreamview_PointCloud_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                apollo.dreamview.PointCloudOuterClass.PointCloud.class, apollo.dreamview.PointCloudOuterClass.PointCloud.Builder.class);
      }

      // Construct using apollo.dreamview.PointCloudOuterClass.PointCloud.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        num_ = emptyFloatList();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return apollo.dreamview.PointCloudOuterClass.internal_static_apollo_dreamview_PointCloud_descriptor;
      }

      @java.lang.Override
      public apollo.dreamview.PointCloudOuterClass.PointCloud getDefaultInstanceForType() {
        return apollo.dreamview.PointCloudOuterClass.PointCloud.getDefaultInstance();
      }

      @java.lang.Override
      public apollo.dreamview.PointCloudOuterClass.PointCloud build() {
        apollo.dreamview.PointCloudOuterClass.PointCloud result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public apollo.dreamview.PointCloudOuterClass.PointCloud buildPartial() {
        apollo.dreamview.PointCloudOuterClass.PointCloud result = new apollo.dreamview.PointCloudOuterClass.PointCloud(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(apollo.dreamview.PointCloudOuterClass.PointCloud result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          num_.makeImmutable();
          result.num_ = num_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof apollo.dreamview.PointCloudOuterClass.PointCloud) {
          return mergeFrom((apollo.dreamview.PointCloudOuterClass.PointCloud)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(apollo.dreamview.PointCloudOuterClass.PointCloud other) {
        if (other == apollo.dreamview.PointCloudOuterClass.PointCloud.getDefaultInstance()) return this;
        if (!other.num_.isEmpty()) {
          if (num_.isEmpty()) {
            num_ = other.num_;
            num_.makeImmutable();
            bitField0_ |= 0x00000001;
          } else {
            ensureNumIsMutable();
            num_.addAll(other.num_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 13: {
                float v = input.readFloat();
                ensureNumIsMutable();
                num_.addFloat(v);
                break;
              } // case 13
              case 10: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                int alloc = length > 4096 ? 4096 : length;
                ensureNumIsMutable(alloc / 4);
                while (input.getBytesUntilLimit() > 0) {
                  num_.addFloat(input.readFloat());
                }
                input.popLimit(limit);
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.Internal.FloatList num_ = emptyFloatList();
      private void ensureNumIsMutable() {
        if (!num_.isModifiable()) {
          num_ = makeMutableCopy(num_);
        }
        bitField0_ |= 0x00000001;
      }
      private void ensureNumIsMutable(int capacity) {
        if (!num_.isModifiable()) {
          num_ = makeMutableCopy(num_, capacity);
        }
        bitField0_ |= 0x00000001;
      }
      /**
       * <code>repeated float num = 1 [packed = true];</code>
       * @return A list containing the num.
       */
      public java.util.List<java.lang.Float>
          getNumList() {
        num_.makeImmutable();
        return num_;
      }
      /**
       * <code>repeated float num = 1 [packed = true];</code>
       * @return The count of num.
       */
      public int getNumCount() {
        return num_.size();
      }
      /**
       * <code>repeated float num = 1 [packed = true];</code>
       * @param index The index of the element to return.
       * @return The num at the given index.
       */
      public float getNum(int index) {
        return num_.getFloat(index);
      }
      /**
       * <code>repeated float num = 1 [packed = true];</code>
       * @param index The index to set the value at.
       * @param value The num to set.
       * @return This builder for chaining.
       */
      public Builder setNum(
          int index, float value) {

        ensureNumIsMutable();
        num_.setFloat(index, value);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>repeated float num = 1 [packed = true];</code>
       * @param value The num to add.
       * @return This builder for chaining.
       */
      public Builder addNum(float value) {

        ensureNumIsMutable();
        num_.addFloat(value);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>repeated float num = 1 [packed = true];</code>
       * @param values The num to add.
       * @return This builder for chaining.
       */
      public Builder addAllNum(
          java.lang.Iterable<? extends java.lang.Float> values) {
        ensureNumIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, num_);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>repeated float num = 1 [packed = true];</code>
       * @return This builder for chaining.
       */
      public Builder clearNum() {
        num_ = emptyFloatList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:apollo.dreamview.PointCloud)
    }

    // @@protoc_insertion_point(class_scope:apollo.dreamview.PointCloud)
    private static final apollo.dreamview.PointCloudOuterClass.PointCloud DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new apollo.dreamview.PointCloudOuterClass.PointCloud();
    }

    public static apollo.dreamview.PointCloudOuterClass.PointCloud getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PointCloud>
        PARSER = new com.google.protobuf.AbstractParser<PointCloud>() {
      @java.lang.Override
      public PointCloud parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PointCloud> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PointCloud> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public apollo.dreamview.PointCloudOuterClass.PointCloud getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apollo_dreamview_PointCloud_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_apollo_dreamview_PointCloud_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n)modules/dreamview/proto/point_cloud.pr" +
      "oto\022\020apollo.dreamview\"\035\n\nPointCloud\022\017\n\003n" +
      "um\030\001 \003(\002B\002\020\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_apollo_dreamview_PointCloud_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_apollo_dreamview_PointCloud_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_apollo_dreamview_PointCloud_descriptor,
        new java.lang.String[] { "Num", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
